//https://github.com/crypti/cryptocurrencies
var cryptocurrencies = {
'42': '42 Coin',
'365': '365Coin',
'404': '404Coin',
'611': 'SixEleven',
'808': '808',
'888': 'Octocoin',
'1337': '1337',
'2015': '2015 coin',
CLUB: ' ClubCoin',
'007': '007 coin',
ZRX: '0x',
BIT16: '16BitCoin',
'1CR': '1Credit',
CHAO: '23 Skidoo',
'2BACCO': '2BACCO Coin',
'2GIVE': '2GiveCoin',
'32BIT': '32Bitcoin',
'3DES': '3DES',
'8BT': '8 Circuit Studios',
'8BIT': '8BIT Coin',
ATKN: 'A-Token',
ABC: 'AB-Chain',
ACT: 'ACT',
ACOIN: 'ACoin',
AXT: 'AIX',
ALIS: 'ALISmedia',
AMIS: 'AMIS',
ARK: 'ARK',
ARNA: 'ARNA Panacea',
ATB: 'ATB coin',
ATCC: 'ATC Coin',
ATFS: 'ATFS Project',
ATL: 'ATLANT',
AXR: 'AXRON',
AEC: 'AcesCoin',
ACES: 'AcesCoin',
ACID: 'AcidCoin',
AMT: 'Acumen',
ACC: 'AdCoin',
ADX: 'AdEx',
ADT: 'AdToken',
ADL: 'Adelphoi',
ADST: 'Adshares',
AIB: 'AdvancedInternetBlock',
ADZ: 'Adzcoin',
AGS: 'Aegis',
AEON: 'AeonCoin',
AERO: 'Aero Coin',
AM: 'AeroMe',
ARN: 'Aeron',
AE: 'Aeternity',
AGRS: 'Agoras Token',
DLT: 'Agrello Delta',
AHT: 'Ahoolee',
AID: 'AidCoin',
ADN: 'Aiden',
AST: 'AirSwap',
AIR: 'AirToken',
ALEX: 'Alexandrite',
PLM: 'Algo.Land',
ALN: 'AlienCoin',
ASAFE: 'Allsafe',
APC: 'AlpaCoin',
ALF: 'AlphaCoin',
ALTCOM: 'AltCommunity Coin',
ALTOCAR: 'AltoCar',
AMBER: 'AmberCoin',
AMB: 'Ambrosus',
AMC: 'AmericanCoin',
AMMO: 'Ammo Rewards',
AMS: 'Amsterdam Coin',
AMY: 'Amygws',
ANCP: 'Anacrypt',
ANAL: 'AnalCoin',
ACP: 'Anarchists Prime',
AND: 'AndromedaCoin',
ANNC: 'AnonCoin',
ANC: 'Anoncoin',
ANTI: 'Anti Bitcoin',
ANTC: 'AntiLitecoin',
APEX: 'ApexCoin',
APPC: 'AppCoins',
APT: 'Aptcoin',
APX: 'Apx',
ARCO: 'AquariusCoin',
ALC: 'Arab League Coin',
ANT: 'Aragon',
ARBI: 'Arbi',
ARB: 'Arbit Coin',
ARCH: 'ArchCoin',
ARC: 'ArcticCoin',
ARDR: 'Ardor',
ARENA: 'Arena',
ARG: 'Argentum',
ARGUS: 'ArgusCoin',
ARI: 'AriCoin',
BOTS: 'ArkDAO',
ARM: 'Armory Coin',
ARPA: 'ArpaCoin',
ABY: 'ArtByte',
ATX: 'ArtexCoin',
ASN: 'Ascension Coin',
XAS: 'Asch',
AC: 'Asia Coin',
ADCN: 'Asiadigicoin',
ATMS: 'Atmos',
ATOM: 'Atomic Coin',
ADC: 'AudioCoin',
REP: 'Augur',
AURS: 'Aureus',
AUR: 'Aurora Coin',
AUTH: 'Authoreon',
ATS: 'Authorship',
AUT: 'Autoria',
AVA: 'Avalon',
AV: 'Avatar Coin',
AVT: 'AventCoin',
AVE: 'Avesta',
ACN: 'AvonCoin',
AXIOM: 'Axiom Coin',
B3: 'B3 Coin',
BAM: 'BAM',
BKX: 'BANKEX',
BERN: 'BERNcash',
VEE: 'BLOCKv',
BOOM: 'BOOM Coin',
BOS: 'BOScoin',
BQC: 'BQCoin',
BAN: 'Babes and Nerds',
NANAS: 'BananaBits',
BNT: 'Bancor Network Token',
'B@': 'BankCoin',
BBCC: 'BaseballCardCoin',
BAT: 'Basic Attention Token',
BTA: 'Bata',
BCX: 'BattleCoin',
BSTK: 'BattleStake',
SAND: 'BeachCoin',
BRDD: 'BeardDollars',
XBTS: 'Beats',
BVC: 'BeaverCoin',
BELA: 'BelaCoin',
BNC: 'Benjacoin',
BEN: 'Benjamins',
BENJI: 'BenjiRolls',
BEST: 'BestChain',
BET: 'BetaCoin',
HUGE: 'BigCoin',
LFC: 'BigLifeCoin',
BIGUP: 'BigUp',
BHC: 'BighanCoin',
BIC: 'Bikercoins',
BLRY: 'BillaryCoin',
XBL: 'Billionaire Token',
BNB: 'Binance Coin',
BIOB: 'BioBar',
BIOS: 'BiosCrypto',
BIP: 'BipCoin',
BIS: 'Bismuth',
BTB: 'BitBar',
BAY: 'BitBay',
BITB: 'BitBean',
BOSS: 'BitBoss',
BRONZ: 'BitBronze',
BCCOIN: 'BitConnect Coin',
BCR: 'BitCredit',
BTCRY: 'BitCrystal',
BCY: 'BitCrystals',
BTCR: 'BitCurrency',
CSNO: 'BitDice',
BFX: 'BitFinex Tokens',
STU: 'BitJob',
BTLC: 'BitLuckCoin',
BTM: 'BitMark',
BTMI: 'BitMiles',
BM: 'BitMoon',
BITOK: 'BitOKX',
BTQ: 'BitQuark',
XSEED: 'BitSeeds',
BSD: 'BitSend',
BST: 'BitStone',
SWIFT: 'BitSwift',
BXT: 'BitTokens',
VEG: 'BitVegan',
VOLT: 'BitVolt',
ZNY: 'BitZeny',
BAC: 'BitalphaCoin',
BXC: 'Bitcedi',
BTD: 'Bitcloud',
BTDX: 'Bitcloud 2.0',
BTC: 'Bitcoin',
BCC: 'Bitcoin Cash',
BCH: 'Bitcoin Cash / BCC',
BTG: 'Bitcoin Gold',
BTPL: 'Bitcoin Planet',
BTCRED: 'Bitcoin Red',
BTCS: 'Bitcoin Scrypt',
BT2: 'Bitcoin SegWit2X',
BTCD: 'BitcoinDark',
BCF: 'BitcoinFast',
XBC: 'BitcoinPlus',
BTCZ: 'BitcoinZ',
BTX: 'Bitcore',
BDL: 'Bitdeal',
BT1: 'Bitfinex Bitcoin Future',
BTCL: 'BitluckCoin',
BMXT: 'Bitmxittz',
BQX: 'Bitquence',
BQ: 'Bitqy',
BRO: 'Bitradio',
BITSD: 'Bits Digit',
BTS: 'Bitshares',
XBS: 'Bitstake',
BITS: 'BitstarCoin',
BITZ: 'Bitz Coin',
BTZ: 'BitzCoin',
BLK: 'BlackCoin',
BS: 'BlackShadowCoin',
BMC: 'Blackmoon Crypto',
BSTAR: 'Blackstar',
BLC: 'BlakeCoin',
BLAS: 'BlakeStar',
BLAZR: 'BlazerCoin',
BLITZ: 'BlitzCoin',
CAT: 'BlockCAT',
BCPT: 'BlockMason Credit Protocol',
BLOCK: 'BlockNet',
BLOCKPAY: 'BlockPay',
BCAP: 'Blockchain Capital',
BLX: 'Blockchain Index',
TIX: 'Blocktix',
BLU: 'BlueCoin',
BDR: 'BlueDragon',
BNX: 'BnrtxCoin',
BOB: 'Bob Coin',
BOG: 'Bogcoin',
BOLI: 'BolivarCoin',
BOMB: 'BombCoin',
BON: 'Bonpay',
BBR: 'Boolberry',
BOST: 'BoostCoin',
BOSON: 'BosonCoin',
CAP: 'BottleCaps',
BOU: 'Boulle',
BSC: 'BowsCoin',
BRAIN: 'BrainCoin',
BRAT: 'Brat',
BRX: 'Breakout Stake',
BRK: 'BreakoutCoin',
BBT: 'BrickBlock',
BRIT: 'BritCoin',
BT: 'BuildTeam',
BULLS: 'BullshitCoin',
BURST: 'BurstCoin',
BUZZ: 'BuzzCoin',
BYC: 'ByteCent',
BTE: 'ByteCoin',
BCN: 'ByteCoin',
GBYTE: 'Byteball',
XCT: 'C-Bits',
CAIx: 'CAIx',
CBD: 'CBD Crystals',
CCC: 'CCCoin',
CETI: 'CETUS Coin',
CINNI: 'CINNICOIN',
CLAM: 'CLAMS',
CMS: 'COMSA',
COSS: 'COSS',
MLS: 'CPROP',
CAB: 'CabbageUnit',
CACH: 'Cachecoin',
CF: 'Californium',
CALC: 'CaliphCoin',
CAM: 'Camcoin',
CMPCO: 'CampusCoin',
CAN: 'CanYaCoin',
CDN: 'Canada eCoin',
CCN: 'CannaCoin',
XCI: 'Cannabis Industry Coin',
CANN: 'CannabisCoin',
AR: 'Cappasity',
CPC: 'CapriCoin',
CTX: 'CarTaxi',
CARBON: 'Carboncoin',
ADA: 'Cardano',
DIEM: 'CarpeDiemCoin',
CTC: 'CarterCoin',
CASH: 'CashCoin',
CSH: 'CashOut',
CAS: 'Cashaa',
CSC: 'CasinoCoin',
CAV: 'Caviar',
CTR: 'Centra',
CNT: 'Centurion',
XCE: 'Cerium',
CHC: 'ChainCoin',
LINK: 'ChainLink',
'4CHN': 'ChanCoin',
CAG: 'Change',
CHA: 'Charity Coin',
CHAT: 'ChatCoin',
CXC: 'CheckCoin',
CHESS: 'ChessCoin',
CHILD: 'ChildCoin',
CNC: 'ChinaCoin',
CHIP: 'Chip',
CHOOF: 'ChoofCoin',
DAY: 'Chronologic',
CRX: 'ChronosCoin',
CIN: 'CinderCoin',
CND: 'Cindicator',
CIR: 'CircuitCoin',
COVAL: 'Circuits of Value',
CVC: 'Civic',
POLL: 'ClearPoll',
CLV: 'CleverCoin',
CHASH: 'CleverHash',
CLICK: 'Clickcoin',
CLINT: 'Clinton',
CLOAK: 'CloakCoin',
CKC: 'Clockcoin',
CLD: 'Cloud',
CLOUT: 'Clout',
CLUD: 'CludCoin',
COE: 'CoEval',
COB: 'Cobinhood',
COX: 'CobraCoin',
CTT: 'CodeTract',
CFC: 'CoffeeCoin',
CFI: 'Cofound.it',
COIN: 'Coin',
XMG: 'Coin Magi',
BTTF: 'Coin to the Future',
C2: 'Coin.2',
CDT: 'CoinDash',
XCJ: 'CoinJob',
LAB: 'CoinWorksCoin',
CTIC: 'Coinmatic',
CNO: 'Coino',
CNMT: 'Coinomat',
CXT: 'Coinonat',
XCXT: 'CoinonatX',
COLX: 'ColossusCoinXT',
CMT: 'CometCoin',
COC: 'Community Coin',
COMM: 'Community Coin',
CMP: 'Compcoin',
CYC: 'ConSpiracy Coin ',
CNL: 'ConcealCoin',
RAIN: 'Condensate',
CFD: 'Confido',
CJT: 'ConnectJob Token',
CQST: 'ConquestCoin',
COOL: 'CoolCoin',
CCX: 'CoolDarkCoin',
CLR: 'CopperLark',
CORAL: 'CoralPay',
CORE: 'Core Group Asset',
COR: 'Corion',
CSMIC: 'Cosmic',
CMC: 'CosmosCoin',
XCP: 'CounterParty',
COV: 'Covesting',
CRAB: 'CrabCoin',
CRACK: 'CrackCoin',
CRC: 'CraftCoin',
CRAFT: 'Craftcoin',
CRAIG: 'CraigsCoin',
CRNK: 'CrankCoin',
CRAVE: 'CraveCoin',
CZC: 'Crazy Coin',
CRM: 'Cream',
XCRE: 'Creatio',
CREA: 'CreativeChain',
CRBIT: 'Creditbit ',
CRE: 'Credits',
CREDO: 'Credo',
CREVA: 'Creva Coin',
WIZ: 'Crowdwiz',
CRW: 'Crown Coin',
CRYPT: 'CryptCoin',
XCR: 'Crypti',
CTO: 'Crypto',
CESC: 'Crypto Escudo',
TKT: 'Crypto Tickets',
C20: 'Crypto20',
CABS: 'CryptoABS',
BUK: 'CryptoBuk',
CBX: 'CryptoBullion',
CCRB: 'CryptoCarbon',
CIRC: 'CryptoCircuits',
FCS: 'CryptoFocus',
CFT: 'CryptoForecast',
TKR: 'CryptoInsight',
CJ: 'CryptoJacks',
CJC: 'CryptoJournal',
CPAY: 'CryptoPay',
CRPS: 'CryptoPennies',
PING: 'CryptoPing',
CS: 'CryptoSpots',
CWXT: 'CryptoWorldXToken',
CDX: 'Cryptodex',
CGA: 'Cryptographic Anomaly',
CYT: 'Cryptokenz',
CIX: 'Cryptonetix',
CNX: 'Cryptonex',
XCN: 'Cryptonite',
MN: 'Cryptsy Mining Contract',
POINTS: 'Cryptsy Points',
CRTM: 'Cryptum',
CVCOIN: 'Crypviser',
CCT: 'Crystal Clear Token ',
QBT: 'Cubits',
CURE: 'Curecoin',
XCS: 'CybCSec Coin',
CC: 'CyberCoin',
CYG: 'Cygnus',
CYP: 'CypherPunkCoin',
DAS: 'DAS',
DRP: 'DCORP',
DIM: 'DIMCOIN',
DMT: 'DMarket',
DRACO: 'DT Token',
DAR: 'Darcrus',
DARK: 'Dark',
DISK: 'Dark Lisk',
MOOND: 'Dark Moon',
DB: 'DarkBit',
DRKC: 'DarkCash',
DCC: 'DarkCrave',
DETH: 'DarkEther',
DGDC: 'DarkGold',
DKC: 'DarkKnightCoin',
DANK: 'DarkKush',
DSB: 'DarkShibe',
DT: 'DarkToken',
DRKT: 'DarkTron',
DNET: 'Darknet',
DSH: 'Dashcoin',
DTB: 'Databits',
DAT: 'Datum',
DTC: 'DayTrader Coin',
XNA: 'DeOxyRibose',
DBTC: 'DebitCoin',
DCT: 'Decent',
DBET: 'Decent.bet',
MANA: 'Decentraland',
HST: 'Decision Token',
DCR: 'Decred',
DEEP: 'Deep Gold',
ONION: 'DeepOnion',
DEA: 'Degas Coin',
DPAY: 'DelightPay',
DCRE: 'DeltaCredits',
DNR: 'Denarius',
DENT: 'Dent',
DCN: 'Dentacoin',
DFBT: 'DentalFix',
DES: 'Destiny',
DTCT: 'DetectorToken',
DVC: 'DevCoin',
DMD: 'Diamond',
DCK: 'DickCoin',
DIGS: 'Diggits',
DGB: 'DigiByte',
DGC: 'DigiCoin',
CUBE: 'DigiCube',
DEUR: 'DigiEuro',
DGT: 'DigiPulse',
DGMS: 'Digigems',
DBG: 'Digital Bullion Gold',
DDF: 'Digital Developers Fund',
DRS: 'Digital Rupees',
DASH: 'DigitalCash',
XDN: 'DigitalNote ',
DP: 'DigitalPrice',
DGD: 'Digix DAO',
DIME: 'DimeCoin',
DCY: 'Dinastycoin',
XDQ: 'Dirac Coin',
DLISK: 'Dlisk',
NOTE: 'Dnotes',
NRN: 'Doc.ai Neuron',
DOGED: 'DogeCoinDark',
DGORE: 'DogeGoreCoin',
XDP: 'DogeParty',
DOGE: 'Dogecoin',
DLC: 'DollarCoin',
DLR: 'DollarOnline',
DRT: 'DomRaider',
DOV: 'DonationCoin',
DOPE: 'DopeCoin',
DOT: 'Dotcoin',
BOAT: 'Doubloon',
DRA: 'DraculaCoin',
DFT: 'Draftcoin',
XDB: 'DragonSphere',
DRGN: 'Dragonchain',
DRM8: 'Dream8Coin',
DTT: 'DreamTeam Token',
DRZ: 'Droidz',
DRC: 'Dropcoin',
DUB: 'DubCoin',
DBIC: 'DubaiCoin',
DBIX: 'DubaiCoin',
DUCK: 'DuckDuckCoin',
DUTCH: 'Dutch Coin',
DUX: 'DuxCoin',
DYN: 'Dynamic',
DTR: 'Dynamic Trading Rights',
ECC: 'E-CurrencyCoin',
EDR: 'E-Dinar Coin',
EFL: 'E-Gulden',
EB3: 'EB3coin',
ECO: 'ECOcoin',
EDRC: 'EDRCoin',
EGO: 'EGOcoin',
EOS: 'EOS',
EQ: 'EQUI',
ERB: 'ERBCoin',
EZC: 'EZCoin',
EZM: 'EZMarket',
EA: 'EagleCoin',
EAGS: 'EagsCoin',
EARTH: 'Earth Token',
EAC: 'EarthCoin',
EMT: 'EasyMine',
EBZ: 'Ebitz',
EBS: 'EbolaShare',
EC: 'Eclipse',
ECOB: 'EcoBit',
EDDIE: 'Eddie coin',
EDGE: 'EdgeCoin',
EDG: 'Edgeless',
EDC: 'EducoinV',
EGG: 'EggCoin',
EDO: 'Eidoo',
EMC2: 'Einsteinium',
EKO: 'EkoCoin',
ELC: 'Elacoin',
XEL: 'Elastic',
ETN: 'Electroneum',
EKN: 'Elektron',
ELE: 'Elementrem',
ELM: 'Elements',
'8S': 'Elite 888',
ELIX: 'Elixir',
ELT: 'Eloplay',
ELS: 'Elysium',
EMB: 'EmberCoin',
MBRS: 'Embers',
EMD: 'Emerald',
EMC: 'Emercoin',
EMIGR: 'EmiratesGoldCoin',
EMPC: 'EmporiumCoin',
EPY: 'Empyrean',
DNA: 'Encrypgen',
ETT: 'EncryptoTel',
ENE: 'EneCoin',
ENRG: 'EnergyCoin',
XNG: 'Enigma',
ENG: 'Enigma',
ENJ: 'Enjin Coin',
ENTER: 'EnterCoin (ENTER)',
EQUAL: 'EqualCoin',
EQT: 'EquiTrader',
EQB: 'Equibit',
EQM: 'Equilibrium Coin',
EFYT: 'Ergo',
ERR: 'ErrorCoin',
ERY: 'Eryllium',
ESP: 'Espers',
ERT: 'Esports.com',
ENT: 'Eternity',
EBET: 'EthBet',
ETB: 'EthBits',
DOGETH: 'EtherDoge',
ETH: 'Ethereum',
BLUE: 'Ethereum Blue',
ECASH: 'Ethereum Cash',
ETC: 'Ethereum Classic',
ETHD: 'Ethereum Dark',
ETG: 'Ethereum Gold',
LNK: 'Ethereum.Link',
ELITE: 'EthereumLite',
ETHS: 'EthereumScrypt',
RIYA: 'Etheriya',
DICE: 'Etheroll',
FUEL: 'Etherparty',
EUC: 'Eurocoin',
ERC: 'EuropeCoin',
EVENT: 'Event Token',
EVC: 'Eventchain',
EGC: 'EverGreenCoin',
EVX: 'Everex',
EVR: 'Everus',
EOC: 'EveryonesCoin',
EVIL: 'EvilCoin',
EXB: 'ExaByte (EXB)',
XUC: 'Exchange Union',
EXN: 'ExchangeN',
EXCL: 'Exclusive Coin',
EXE: 'ExeCoin',
EXIT: 'ExitCoin',
EXP: 'Expanse',
EON: 'Exscudo',
XSB: 'Extreme Sportsbook',
XT: 'ExtremeCoin',
F16: 'F16Coin',
FX: 'FCoin',
FIBRE: 'FIBRE',
FLASH: 'FLASH coin',
FLIK: 'FLiK',
FC: 'Facecoin',
FCT: 'Factoids',
FAIR: 'FairCoin',
FAME: 'FameCoin',
FCN: 'FantomCoin ',
FST: 'FastCoin',
DROP: 'FaucetCoin',
FAZZ: 'FazzCoin',
FTC: 'FeatherCoin',
FIL: 'FileCoin',
FIND: 'FindCoin',
FIRE: 'FireCoin',
FRC: 'FireRoosterCoin',
FFC: 'FireflyCoin',
'1ST': 'FirstBlood',
FIRST: 'FirstCoin',
FRST: 'FirstCoin',
FIST: 'FistBump',
FIT: 'Fitcoin',
FLAP: 'Flappy Coin',
FLX: 'Flash',
FLVR: 'FlavorCoin',
FLO: 'FlorinCoin',
FLT: 'FlutterCoin',
FLY: 'FlyCoin',
FLDC: 'Folding Coin',
FLLW: 'Follow Coin',
FONZ: 'FonzieCoin',
FDC: 'FoodCoin',
XFC: 'Forever Coin',
FOREX: 'ForexCoin',
FRAC: 'FractalCoin',
FRN: 'Francs',
FRK: 'Franko',
FRWC: 'Frankywillcoin',
FRAZ: 'FrazCoin',
FGZ: 'Free Game Zone',
FRE: 'FreeCoin',
FSC2: 'FriendshipCoin',
FUCK: 'Fuck Token',
FC2: 'Fuel2Coin',
FJC: 'FujiCoin',
NTO: 'Fujinto',
FUNC: 'FunCoin',
FUN: 'FunFair',
FND: 'FundRequest',
FYN: 'FundYourselfNow',
FSN: 'Fusion',
FUTC: 'FutCoin',
FTP: 'FuturePoints',
FUZZ: 'Fuzzballs',
GAIA: 'GAIA Platform',
GAKH: 'GAKHcoin',
GAT: 'GAT Coin',
GBRC: 'GBR Coin',
GCN: 'GCoin',
GIZ: 'GIZMOcoin',
GPU: 'GPU Coin',
GSM: 'GSM Coin',
GES: 'Galaxy eSolutions',
GLX: 'GalaxyCoin',
GAM: 'Gambit coin',
GBT: 'GameBetCoin',
GML: 'GameLeagueCoin',
UNITS: 'GameUnits',
GAME: 'Gamecredits',
FLP: 'Gameflip',
GNJ: 'GanjaCoin V2',
GAP: 'Gapcoin',
GAS: 'Gas',
GAY: 'GayCoin',
GEMZ: 'Gemz Social',
GSY: 'GenesysCoin',
GEN: 'Genstake',
GEO: 'GeoCoin',
GUNS: 'GeoFunders',
SPKTR: 'Ghost Coin',
GHC: 'GhostCoin',
GHOUL: 'Ghoul Coin',
GIFT: 'GiftNet',
GIG: 'GigCoin',
GHS: 'Giga Hash',
WTT: 'Giga Watt',
GGS: 'Gilgam',
GIM: 'Gimli',
GOT: 'Giotto Coin',
GIVE: 'GiveCoin',
GLA: 'Gladius',
GLOBE: 'Global',
GCR: 'Global Currency Reserve',
GJC: 'Global Jobcoin',
BSTY: 'GlobalBoost',
GLC: 'GlobalCoin',
GSX: 'GlowShares',
GLYPH: 'GlyphCoin',
GNO: 'Gnosis',
GOAT: 'Goat',
GOKU: 'Gokucoin',
GPL: 'Gold Pressed Latinum',
GB: 'GoldBlocks',
GLD: 'GoldCoin',
MNT: 'GoldMint',
GP: 'GoldPieces',
XGR: 'GoldReserve',
XGB: 'GoldenBird',
GMX: 'Goldmaxcoin',
GNT: 'Golem Network Token',
GOLOS: 'Golos',
GOOD: 'GoodCoin',
GOON: 'Goonies',
GOTX: 'GothicCoin',
GRF: 'Graft Network',
GRAM: 'Gram Coin',
GDC: 'GrandCoin',
GRT: 'Grantcoin',
GRAV: 'Graviton',
GBIT: 'GravityBit',
GRE: 'GreenCoin',
GREXIT: 'GrexitCoin',
GRC: 'GridCoin',
GRM: 'GridMaster',
GRID: 'GridPay',
GMC: 'Gridmaster',
GRS: 'Groestlcoin ',
GRWI: 'Growers International',
GROW: 'GrownCoin',
GRW: 'GrowthCoin',
GCC: 'GuccioneCoin',
GUE: 'GuerillaCoin',
NLG: 'Gulden',
GUP: 'Guppy',
GXC: 'Gx Coin',
PLAY: 'HEROcoin',
HODL: 'HOdlcoin',
HTML5: 'HTML Coin',
HKG: 'Hacker Gold',
HAC: 'Hackspace Capital',
HAL: 'Halcyon',
HALLO: 'Halloween Coin',
HAMS: 'HamsterCoin',
HPC: 'HappyCoin',
HCC: 'HappyCreatorCoin ',
HRB: 'Harbour DAO',
HZT: 'HazMatCoin',
HAZE: 'HazeCoin',
WORM: 'HealthyWorm',
HEAT: 'Heat Ledger',
HVC: 'HeavyCoin',
HDG: 'Hedge Token',
HEDG: 'Hedgecoin',
HEEL: 'HeelCoin',
HNC: 'Hellenic Coin',
HGT: 'Hello Gold',
HMP: 'HempCoin',
HXT: 'HextraCoin',
HXX: 'HexxCoin',
XHI: 'HiCoin',
HVCO: 'High Voltage Coin',
HIRE: 'HireMatch',
HTC: 'Hitcoin',
HVN: 'Hive',
HBN: 'HoboNickels',
HONEY: 'Honey',
HZ: 'Horizon',
HSP: 'Horse Power',
HSR: 'Hshare',
HBT: 'Hubiit',
HMQ: 'Humaniq',
HUC: 'HunterCoin',
HUSH: 'Hush',
H2O: 'Hydrominer',
HYPER: 'HyperCoin',
HYP: 'Hyperstake',
I0C: 'I0coin',
ICASH: 'ICASH',
ICOO: 'ICO OpenLedger',
ICOS: 'ICOBox',
ICX: 'ICON Project',
ILC: 'ILCoin',
ILCT: 'ILCoin Token',
IML: 'IMMLA',
INS: 'INS Ecosystem',
IOC: 'IOCoin',
IOT: 'IOTA',
IOU: 'IOU1',
IXC: 'IXcoin',
ROCK: 'Ice Rock Mining',
ICB: 'IceBergCoin',
ICOB: 'Icobid',
ICON: 'Iconic',
ICN: 'Iconomi',
IGNIS: 'Ignis',
IMX: 'Impact',
IMPCH: 'Impeach',
IPC: 'ImperialCoin',
IMPS: 'Impulse Coin',
IN: 'InCoin',
INPAY: 'InPay',
NKA: 'IncaKoin',
INCNT: 'Incent',
INCP: 'InceptionCoin',
INC: 'Incrementum',
IMS: 'Independent Money System',
INDI: 'IndiCoin',
IND: 'Indorse',
IFC: 'Infinite Coin',
XIN: 'Infinity Economics',
INF8: 'Infinium-8',
IFLT: 'InflationCoin',
INFX: 'Influxcoin',
INN: 'Innova',
INSN: 'Insane Coin',
INSANE: 'InsaneCoin',
WOLF: 'Insanity Coin',
MINE: 'Instamine Nuggets',
ITT: 'Intelligent Trading Technologies',
IOP: 'Internet of People',
INXT: 'Internxt',
IFT: 'InvestFeed',
INV: 'Invictus',
IVZ: 'InvisibleCoin',
ION: 'Ionomy',
ISL: 'IslaCoin',
IEC: 'IvugeoEvolutionCoin',
IWT: 'IwToken',
JIO: 'JIO Token',
JPC: 'JackPotCoin',
JANE: 'JaneCoin',
JNS: 'Janus',
JVY: 'Javvy',
JWL: 'Jewels',
JIF: 'JiffyCoin',
JCR: 'Jincor',
JOBS: 'JobsCoin',
J: 'JoinCoin',
JOK: 'JokerCoin',
XJO: 'JouleCoin',
JUDGE: 'JudgeCoin',
JBS: 'JumBucks Coin',
JKC: 'JunkCoin',
JDC: 'JustDatingSite',
KAT: 'KATZcoin',
KRC: 'KRCoin',
KAPU: 'Kapu',
KRB: 'Karbowanec',
KARM: 'Karmacoin',
KAYI: 'Kayı',
KEK: 'KekCoin',
KCN: 'Kencoin',
KC: 'Kernalcoin',
KEX: 'KexCoin',
KICK: 'KickCoin',
KLC: 'KiloCoin',
KIN: 'Kin',
KING: 'King93',
KED: 'Klingon Empire Darsek',
KDC: 'Klondike Coin',
KOBO: 'KoboCoin',
KOLION: 'Kolion',
KMD: 'Komodo',
KORE: 'Kore',
KRAK: 'Kraken',
KRONE: 'Kronecoin',
KGC: 'KrugerCoin',
KTK: 'KryptCoin',
KR: 'Krypton',
KUBO: 'KubosCoin',
KCS: 'Kucoin',
KURT: 'Kurrent',
KUSH: 'KushCoin',
KNC: 'Kyber Network',
LA: 'LAToken',
LBC: 'LBRY Credits',
LEO: 'LEOcoin',
LGBTQ: 'LGBTQoin',
LIFE: 'LIFE',
LTBC: 'LTBCoin',
LUX: 'LUXCoin',
PIX: 'Lampix',
LANA: 'LanaCoin',
LTH: 'Lathaan',
LAT: 'Latium',
LAZ: 'Lazarus',
LEPEN: 'LePenCoin',
LEA: 'LeaCoin',
LGD: 'Legends Cryptocurrency',
LEMON: 'LemonCoin',
LENIN: 'LeninCoin',
LIR: 'Let it Ride',
LVG: 'Leverage Coin',
LEV: 'Leverj',
XLC: 'LeviarCoin',
XLB: 'LibertyCoin',
LXC: 'LibrexCoin',
LSD: 'LightSpeedCoin',
LIMX: 'LimeCoinX',
LTD: 'Limited Coin',
LINDA: 'Linda',
LINX: 'Linx',
LQD: 'Liquid',
LSK: 'Lisk',
LBTC: 'LiteBitcoin',
LTCR: 'LiteCreed',
LDOGE: 'LiteDoge',
LTB: 'Litebar ',
LTC: 'Litecoin',
LCASH: 'LitecoinCash',
LTCD: 'LitecoinDark',
LTCX: 'LitecoinX',
LTS: 'Litestar Coin',
LTA: 'Litra',
LIV: 'LiviaCoin',
LOAN: 'Loan',
LOC: 'Loco',
LMC: 'LomoCoin',
LOOK: 'LookCoin',
LRC: 'Loopring',
BASH: 'LuckChain',
LK7: 'Lucky7Coin',
LUCKY: 'LuckyBlocks (LUCKY)',
LKY: 'LuckyCoin',
LUN: 'Lunyr',
LC: 'Lutetium Coin',
LYC: 'LycanCoin',
LKK: 'Lykke',
LYB: 'LyraBar',
MCAP: 'MCAP',
MIS: 'MIScoin',
MMNXT: 'MMNXT ',
MMXVI: 'MMXVI',
MAC: 'MachineCoin',
MCRN: 'MacronCoin',
MRV: 'Macroverse',
ART: 'Maecenas',
MAG: 'Magos',
MAID: 'MaidSafe Coin',
MMXIV: 'MaieutiCoin',
MIV: 'MakeItViral',
MKR: 'Maker',
MAPC: 'MapCoin',
MAR: 'MarijuanaCoin',
MRS: 'MarsCoin',
MARS: 'MarsCoin ',
MXT: 'MartexCoin',
MARV: 'Marvelous',
MARX: 'MarxCoin',
MARYJ: 'MaryJane Coin',
MSR: 'Masari',
MC: 'Mass Coin',
MASS: 'Mass.Cloud',
MCAR: 'MasterCar',
MSC: 'MasterCoin',
MM: 'MasterMint',
MTR: 'MasterTraderCoin',
MTX: 'Matryx',
MAX: 'MaxCoin',
MYC: 'MayaCoin',
MZC: 'MazaCoin',
MBIT: 'Mbitbooks',
MLITE: 'MeLite',
MEDI: 'MediBond',
MDC: 'MedicCoin',
MED: 'MediterraneanCoin',
MPRO: 'MediumProject',
MEC: 'MegaCoin',
MEGA: 'MegaFlash',
XMS: 'Megastake',
MLN: 'Melon',
MET: 'Memessenger',
MMC: 'MemoryCoin',
MER: 'Mercury',
MTL: 'Metal',
MTLM3: 'Metal Music v3',
METAL: 'MetalCoin',
ETP: 'Metaverse',
MDT: 'Midnight ',
MUU: 'MilkCoin',
MIL: 'Milllionaire Coin',
MILO: 'MiloCoin',
MNC: 'MinCoin',
MG: 'Mind Gene',
MND: 'MindCoin',
MIN: 'Minerals Coin',
MNE: 'Minereum',
MRT: 'MinersReward',
MNM: 'Mineum',
MINEX: 'Minex',
MAT: 'MiniApps',
MINT: 'MintCoin',
MGO: 'MobileGo',
MOBI: 'Mobius',
MDL: 'Modulum',
MOD: 'Modum',
MDA: 'Moeda',
MOIN: 'MoinCoin',
MOJO: 'Mojocoin',
TAB: 'MollyCoin',
MONA: 'MonaCoin',
MCO: 'Monaco',
XMCC: 'MonacoCoin',
MNZ: 'Monaize',
XMR: 'Monero',
MONETA: 'Moneta',
MCN: 'MonetaVerde',
MUE: 'MonetaryUnit',
MTH: 'Monetha',
MONEY: 'MoneyCoin',
MNY: 'Monkey',
MBI: 'Monster Byte Inc',
MOON: 'MoonCoin',
MRP: 'MorpheusCoin',
MSP: 'Mothership',
MOTO: 'Motocoin',
MTK: 'Moya Token',
MRSA: 'MrsaCoin',
MUDRA: 'MudraCoin',
MWC: 'MultiWallet Coin',
MBT: 'Multibot',
MRY: 'MurrayCoin',
MUSIC: 'Musiccoin',
MCI: 'Musiconomi',
MST: 'MustangCoin',
MYB: 'MyBit',
MT: 'Mycelium Token',
XMY: 'MyriadCoin',
MYST: 'Mysterium',
XEM: 'NEM',
NEO: 'NEO',
NEOG: 'NEO Gold',
NPC: 'NPCcoin',
NVST: 'NVO',
NXE: 'NXEcoin',
NXTI: 'NXTI',
NXTTY: 'NXTTY',
NKT: 'NakomotoDark',
NMC: 'NameCoin',
NAMO: 'NamoCoin',
NAN: 'NanoToken',
NPX: 'Napoleon X',
NAS2: 'Nas2Coin',
NAUT: 'Nautilus Coin',
NAV: 'NavCoin',
NEBL: 'Neblio',
NEBU: 'Nebuchadnezzar',
NEF: 'NefariousCoin',
NEC: 'NeoCoin',
NEOS: 'NeosCoin',
NTCC: 'NeptuneClassic',
NBIT: 'NetBit',
NET: 'NetCoin',
NTM: 'NetM',
NETKO: 'Netko',
NETC: 'NetworkCoin',
NEU: 'NeuCoin',
NRC: 'Neurocoin',
NTRN: 'Neutron',
NEVA: 'NevaCoin',
NDC: 'NeverDie',
NIC: 'NewInvestCoin',
NYC: 'NewYorkCoin',
NZC: 'NewZealandCoin',
NEWB: 'Newbium',
NXC: 'Nexium',
NXS: 'Nexus',
NICE: 'NiceCoin',
NMB: 'Nimbus Coin',
NIMFA: 'Nimfamoney',
NTC: 'NineElevenTruthCoin',
NDOGE: 'NinjaDoge',
NLC2: 'NoLimitCoin',
NLC: 'NoLimitCoin',
NOBL: 'NobleCoin',
NODE: 'Node',
NRB: 'NoirBits',
NRS: 'NoirShares',
NOO: 'Noocoin',
NVC: 'NovaCoin',
NBT: 'NuBits',
NSR: 'NuShares',
NUBIS: 'NubisCoin',
NUKE: 'NukeCoin',
NKC: 'Nukecoinz',
NULS: 'Nuls',
N7: 'Number7',
NUM: 'NumbersCoin',
NMR: 'Numerai',
NXT: 'Nxt',
NYAN: 'NyanCoin',
NBL: 'Nybble',
ODMC: 'ODMCoin',
OK: 'OKCash',
OBITS: 'Obits Coin',
OBS: 'Obscurebay',
ODN: 'Obsidian',
OCL: 'Oceanlab',
OTX: 'Octanox',
OCTO: 'OctoCoin',
ODNT: 'Old Dogs New Tricks',
OLDSF: 'OldSafeCoin',
OLV: 'OldV',
OLYMP: 'OlympCoin',
OMA: 'OmegaCoin',
OMG: 'OmiseGo',
OMNI: 'Omni',
OMC: 'OmniCron',
ONX: 'Onix',
XPO: 'Opair',
OPAL: 'OpalCoin',
OTN: 'Open Trading Network',
OAX: 'OpenANX',
OSC: 'OpenSourceCoin',
ZNT: 'OpenZen',
OPES: 'Opes',
OPP: 'Opporty',
OPTION: 'OptionCoin',
OPT: 'Opus',
OC: 'OrangeCoin',
ORB: 'Orbitcoin',
ORLY: 'OrlyCoin',
ORME: 'Ormeus Coin',
ORO: 'OroCoin',
OROC: 'Orocrypt',
OS76: 'OsmiumCoin',
OXY: 'Oxycoin',
PQT: 'PAquarium',
PLNC: 'PLNCoin',
PSI: 'PSIcoin',
PX: 'PXcoin',
PCS: 'Pabyosi Coin',
PBC: 'PabyosiCoin',
PAC: 'PacCoin',
PAK: 'Pakcoin',
PND: 'PandaCoin',
PINKX: 'PantherCoin',
PRP: 'Papyrus',
PRG: 'Paragon',
DUO: 'ParallelCoin',
PARA: 'ParanoiaCoin',
PKB: 'ParkByte',
PART: 'Particl',
PASC: 'Pascal Coin',
PASL: 'Pascal Lite',
PTOY: 'Patientory',
PYC: 'PayCoin',
XPY: 'PayCoin',
PAYP: 'PayPeer',
PPP: 'PayPie',
PYN: 'Paycentos',
CON_: 'Paycon',
PEC: 'PeaceCoin',
XPB: 'Pebble Coin',
PPC: 'PeerCoin',
GUESS: 'Peerguess',
PPY: 'Peerplays',
PEN: 'PenCoin',
PTA: 'PentaCoin',
MEME: 'Pepe',
PEPECASH: 'Pepe Cash',
PIE: 'Persistent Information Exchange',
PTC: 'PesetaCoin',
PSB: 'PesoBit',
XPD: 'PetroDollar',
PXL: 'Phalanx',
XPH: 'PharmaCoin',
PHS: 'PhilosophersStone',
PXC: 'PhoenixCoin',
PHR: 'Phreak',
PIGGY: 'Piggy Coin',
PLR: 'Pillar',
PINK: 'PinkCoin',
PIO: 'Pioneershares',
PIRL: 'Pirl',
PIZZA: 'PizzaCoin',
PLANET: 'PlanetCoin',
PNC: 'PlatiniumCoin',
PKT: 'Playkey',
PLU: 'Pluton',
POE: 'Po.et',
POS: 'PoSToken',
POSW: 'PoSWallet',
XPS: 'PoisonIvyCoin',
XPOKE: 'PokeChain',
POLY: 'PolyBit',
PLBT: 'Polybius',
XSP: 'PoolStamp',
PPT: 'Populous',
PEX: 'PosEx',
TRON: 'Positron',
POST: 'PostCoin',
POT: 'PotCoin',
POWR: 'Power Ledger',
PWR: 'PowerCoin',
PRE: 'Premium',
HILL: 'President Clinton',
PRES: 'President Trump',
PBT: 'Primalbase',
PST: 'Primas',
PXI: 'Prime-X1',
PRIME: 'PrimeChain',
XPM: 'PrimeCoin',
PRX: 'Printerium',
PRM: 'PrismChain',
PIVX: 'Private Instant Verified Transaction',
PRIX: 'Privatix',
PZM: 'Prizm',
XPRO: 'ProCoin',
PROC: 'ProCurrency',
PCM: 'Procom',
PDC: 'Project Decorum',
ZEPH: 'Project Zephyr',
PRO: 'Propy',
VRP: 'Prosense.tv',
PGL: 'Prospectors',
PRC: 'ProsperCoin',
PSEUD: 'PseudoCash',
PSY: 'Psilocybin',
PULSE: 'Pulse',
PUPA: 'PupaCoin',
PURA: 'Pura',
PURE: 'Pure',
VIDZ: 'PureVidz',
PUT: 'PutinCoin',
QTUM: 'QTUM',
QORA: 'QoraCoin',
QBK: 'QuBuck Coin',
QAU: 'Quantum',
QRL: 'Quantum Resistant Ledger',
QRK: 'QuarkCoin',
QTZ: 'Quartz',
QTL: 'Quatloo',
QCN: 'Quazar Coin',
QBC: 'Quebecoin',
QSLV: 'Quicksilver coin',
XQN: 'Quotient',
QVT: 'Qvolta',
QWARK: 'Qwark',
REAL: 'REAL',
REX: 'REX',
RGC: 'RG Coin',
ROS: 'ROS Coin',
RADI: 'RadicalCoin',
RADS: 'Radium',
RDN: 'RadonPay',
XRB: 'RaiBlocks',
XRA: 'Ratecoin',
RATIO: 'Ratio',
RZR: 'RazorCoin',
REA: 'Realisto',
RCC: 'Reality Clash',
REBL: 'Rebellious',
RRT: 'Recovery Right Tokens',
RPX: 'Red Pulse',
RCX: 'RedCrowCoin',
RED: 'Redcoin',
RDD: 'ReddCoin',
REE: 'ReeCoin',
REC: 'Regalcoin',
RNDR: 'Render Token',
RNS: 'RenosCoin',
REQ: 'Request Network',
RMS: 'Resumeo Shares',
RBIT: 'ReturnBit',
RNC: 'ReturnCoin',
R: 'Revain',
REV: 'Revenu',
XRE: 'RevolverCoin',
RHEA: 'Rhea',
XRL: 'Rialto.AI',
RBR: 'Ribbit Rewards',
RICE: 'RiceCoin',
RIDE: 'Ride My Car',
RIC: 'Riecoin',
RBT: 'Rimbit',
RING: 'RingCoin',
RIPO: 'RipOffCoin',
RCN: 'Ripio',
XRP: 'Ripple',
RBX: 'RiptoBuX',
RISE: 'Rise',
RVT: 'Rivetz',
ROK: 'Rockchain',
RPC: 'RonPaulCoin',
ROOT: 'RootCoin',
ROOTS: 'RootProject',
RT2: 'RotoCoin',
ROUND: 'RoundCoin',
RKC: 'Royal Kingdom Coin',
ROYAL: 'RoyalCoin',
RYC: 'RoyalCoin',
RYCN: 'RoyalCoin 2.0',
RBIES: 'Rubies',
RUBIT: 'Rublebit',
RBY: 'RubyCoin',
RUPX: 'Rupaya',
RUP: 'Rupee',
RC: 'Russiacoin',
RUST: 'RustCoin',
RUSTBITS: 'Rustbits',
S8C: 'S88 Coin',
SAR: 'SARCoin',
SMNX: 'SMNX',
SNM: 'SONM',
SSV: 'SSVCoin',
STS: 'STRESScoin',
SAFEX: 'SafeExchangeCoin',
SFE: 'Safecoin',
SFR: 'SaffronCoin',
SALT: 'Salt Lending',
SLS: 'SaluS',
SMSR: 'Samsara Coin',
SND: 'Sandcoin',
SAN: 'Santiment',
XAI: 'SapienceCoin',
STV: 'Sativa Coin',
MAD: 'SatoshiMadness',
SAT2: 'Saturn2Coin',
STO: 'Save The Ocean',
SANDG: 'Save and Gain',
SCORE: 'Scorecoin',
SCOR: 'Scorista',
SCOT: 'Scotcoin',
SCRPT: 'ScryptCoin',
SCT: 'ScryptToken',
SRT: 'Scrypto',
SCRT: 'SecretCoin',
SRC: 'SecureCoin',
SEEDS: 'SeedShares',
SEL: 'SelenCoin',
KEY: 'SelfKey',
SNS: 'Sense',
SENSE: 'Sense Token',
SEN: 'Sentaro',
SEQ: 'Sequence',
SP: 'Sex Pistols',
SXC: 'SexCoin',
SHADE: 'ShadeCoin',
SDC: 'ShadowCash',
SAK: 'SharkCoin',
SHP: 'Sharpe Capital',
SHLD: 'ShieldCoin',
SHIFT: 'Shift',
SH: 'Shilling',
SHORTY: 'ShortyCoin',
SC: 'Siacoin',
SIB: 'SibCoin',
SIGT: 'Signatum',
SILK: 'SilkCoin',
ST: 'SimpleToken',
SIGU: 'Singular',
SNGLS: 'SingularDTV',
SKIN: 'Skincoin',
SKR: 'Skrilla Token',
SKB: 'SkullBuzz',
SKY: 'Skycoin',
SLM: 'SlimCoin',
SLING: 'Sling Coin',
SIFT: 'Smart Investment Fund Token',
SMART: 'SmartCash',
SMC: 'SmartCoin',
SMLY: 'SmileyCoin',
SMF: 'SmurfCoin',
SNOV: 'Snovio',
SMAC: 'Social Media Coin',
SMT: 'Social Media Market',
SCL: 'Social Nexus',
SOCC: 'SocialCoin',
XBOT: 'SocialXbotCoin',
SOIL: 'SoilCoin',
SOJ: 'Sojourn Coin',
SDAO: 'Solar DAO',
SLR: 'SolarCoin',
CELL: 'SolarFarm',
SFC: 'Solarflarecoin',
XLR: 'Solaris',
SOLE: 'SoleCoin',
SONG: 'Song Coin',
SSD: 'Sonic Screw Driver Coin',
SOON: 'SoonCoin',
SPHTX: 'SophiaTX',
SNK: 'Sosnovkino',
SOUL: 'SoulCoin',
SCASH: 'SpaceCash',
SPACE: 'SpaceCoin',
SPA: 'SpainCoin',
SPEC: 'SpecCoin',
SPX: 'Specie',
XSPEC: 'Spectre',
SPHR: 'Sphere Coin',
XID: 'Sphre AIR',
SPC: 'SpinCoin',
SPN: 'Spoon',
SPORT: 'SportsCoin',
SPOTS: 'Spots',
SPT: 'Spots',
SPR: 'Spreadcoin',
SPRTS: 'Sprouts',
SQP: 'SqPay',
SQL: 'Squall Coin',
XSI: 'Stability Shares',
SBC: 'StableCoin',
STCN: 'Stakecoin',
STHR: 'Stakerush',
STALIN: 'StalinCoin',
STAR: 'Starbase',
START: 'StartCoin',
STA: 'Starta',
SNT: 'Status Network Token',
XST: 'StealthCoin',
PNK: 'SteamPunk',
STEEM: 'Steem',
SBD: 'Steem Backed Dollars',
XLM: 'Stellar',
STEPS: 'Steps',
SLG: 'SterlingCoin',
STOCKBET: 'StockBet',
STORJ: 'Storj',
SJCX: 'StorjCoin',
STORM: 'Storm',
STX: 'Stox',
STRAT: 'Stratis',
DATA: 'Streamr DATAcoin',
SUB: 'Substratum Network',
SUMO: 'Sumokoin',
SNC: 'SunContract',
SSTC: 'SunShotCoin',
SUP: 'Supcoin',
SUPER: 'SuperCoin',
UNITY: 'SuperNET',
M1: 'SupplyShock',
SPM: 'Supreme',
SUR: 'Suretly',
BUCKS: 'SwagBucks',
SWT: 'Swarm City Token',
SWARM: 'SwarmCoin',
SWEET: 'SweetStake',
SWING: 'SwingCoin',
SCN: 'Swiscoin',
SDP: 'SydPakCoin',
SYNC: 'SyncCoin',
SYC: 'SynchroCoin',
SYNX: 'Syndicate',
AMP: 'Synereo',
SNRG: 'Synergy',
SYS: 'SysCoin',
BAR: 'TBIS token',
TDFB: 'TDFB',
TAG: 'TagCoin',
TAJ: 'TajCoin',
TAK: 'TakCoin',
TAM: 'TamaGucci',
TTT: 'Tap Project',
TAP: 'TappingCoin',
TAT: 'Tatiana Coin',
TSE: 'TattooCoin',
TEC: 'TeCoin',
TEAM: 'TeamUP',
TECH: 'TechCoin',
THS: 'TechShares',
TEK: 'TekCoin',
TELL: 'Tellurion',
PAY: 'TenX',
TENNET: 'Tennet',
TRC: 'TerraCoin',
TER: 'TerraNovaCoin',
TESLA: 'TeslaCoilCoin',
TES: 'TeslaCoin',
USDT: 'Tether',
TRA: 'Tetra',
XTZ: 'Tezos',
THNX: 'ThankYou',
THC: 'The Hempcoin',
XVE: 'The Vegan Initiative',
CHIEF: 'TheChiefCoin',
TCR: 'Thecreed',
MAY: 'Theresa May Coin',
TAGR: 'Think And Get Rich Coin',
TIA: 'Tianhe',
TNT: 'Tierion',
TIE: 'Ties Network',
TGC: 'TigerCoin',
XTC: 'TileCoin',
TIME: 'Time',
TME: 'Timereum',
TMC: 'TimesCoin',
TIT: 'TitCoin',
TTC: 'TittieCoin',
TMT: 'ToTheMoon',
TODAY: 'TodayCoin',
TAAS: 'Token as a Service',
TKN: 'TokenCard  ',
ACE: 'TokenStars',
TKS: 'Tokes',
TOM: 'Tomahawkcoin',
TOR: 'TorCoin',
TOT: 'TotCoin',
MTN: 'TrackNetToken',
TRCT: 'Tracto',
TIO: 'Trade.io',
TX: 'Transfer',
TBCX: 'TrashBurn',
TRV: 'Travel Coin',
TZC: 'TrezarCoin',
TRI: 'Triangles Coin',
TRIBE: 'TribeToken',
TRICK: 'TrickyCoin',
TRIG: 'Trigger',
TRIP: 'Trippki',
TPG: 'Troll Payment',
TPAY: 'TrollPlay',
TRX: 'Tronix',
TRK: 'TruckCoin',
TFL: 'True Flip Lottery',
TIC: 'TrueInvestmentCoin',
TRUMP: 'TrumpCoin',
TRST: 'TrustCoin',
TRUST: 'TrustPlus',
TUR: 'Turron',
TWLV: 'Twelve Coin',
TWIST: 'TwisterCoin',
UFO: 'UFO Coin',
XUP: 'UPcoin',
UR: 'UR',
UBQ: 'Ubiq',
UBIQ: 'Ubiqoin',
U: 'Ucoin',
USC: 'Ultimate Secure Cash',
UTC: 'UltraCoin',
ULTC: 'Umbrella',
UMC: 'Umbrella Coin',
UNC: 'UnCoin',
UNAT: 'Unattanium',
UNB: 'UnbreakableCoin',
UNF: 'Unfed Coin',
UNIFY: 'Unify',
UNIKRN: 'UnikoinGold',
UKG: 'UnikoinGold',
UNIQ: 'Uniqredit',
USDE: 'UnitaryStatus Dollar',
UAEC: 'United Arab Emirates Coin',
UIS: 'Unitus',
UNIT: 'Universal Currency',
UNI: 'Universe',
UNO: 'Unobtanium',
UP: 'UpToken',
URO: 'UroCoin',
UET: 'Useless Ethereum Token',
UTH: 'Uther',
UTIL: 'Utility Coin',
UTK: 'Utrust',
VIBE: 'VIBEHub',
VIP: 'VIP Tokens',
VIVO: 'VIVO Coin',
VPRC: 'VapersCoin',
VAPOR: 'Vaporcoin',
VLTC: 'VaultCoin',
XVC: 'Vcash',
VEN: 'Vechain',
VEC2: 'VectorCoin 2.0 ',
VLT: 'Veltor',
VNT: 'Veredictum',
XVG: 'Verge',
VRC: 'VeriCoin',
VERI: 'Veritaseum',
VRM: 'Verium',
VRS: 'Veros',
VERSA: 'Versa Token',
VTC: 'VertCoin',
VTX: 'Vertex',
VZT: 'Vezt',
VIA: 'ViaCoin',
VIB: 'Viberate',
VTY: 'Victoriouscoin',
VDO: 'VidioCoin',
VIOR: 'ViorCoin',
VIRAL: 'Viral Coin',
VUC: 'Virta Unique Coin',
VTA: 'VirtaCoin',
XVP: 'VirtacoinPlus',
VMC: 'VirtualMining Coin',
VISIO: 'Visio',
VOISE: 'Voise',
VOOT: 'VootCoin',
VOX: 'Voxels',
VOYA: 'Voyacoin',
VSX: 'Vsync',
VTR: 'Vtorrent',
WMC: 'WMCoin',
WRT: 'WRTcoin',
WABI: 'WaBi',
WGR: 'Wagerr',
WTC: 'Waltonchain',
WAN: 'Wanchain',
WAND: 'WandX',
WARP: 'WarpCoin',
WASH: 'WashingtonCoin',
WAVES: 'Waves',
WCT: 'Waves Community Token',
WGO: 'WavesGO',
WNET: 'Wavesnode.net',
WAY: 'WayCoin',
WSX: 'WeAreSatoshi',
WPR: 'WePower',
WEALTH: 'WealthCoin',
WEB: 'Webcoin',
WEX: 'Wexcoin',
WHL: 'WhaleCoin',
WC: 'WhiteCoin',
XWC: 'WhiteCoin',
WIC: 'Wi Coin',
WBB: 'Wild Beast Coin',
WILD: 'Wild Crypto',
WINE: 'WineCoin',
WINGS: 'Wings DAO',
WINK: 'Wink',
WISC: 'WisdomCoin',
WSC: 'WiserCoin',
WISH: 'Wish Finance',
WOLK: 'Wolk',
WOMEN: 'WomenCoin',
LOG: 'Wood Coin',
WGC: 'World Gold Coin',
XWT: 'World Trade Funds',
WDC: 'WorldCoin',
WOP: 'WorldPay',
WRC: 'Worldcore',
WAX: 'Worldwide Asset eXchange',
WYR: 'Wyrify',
XRED: 'X Real Estate Development',
XC: 'X11 Coin',
X2: 'X2Coin',
XCO: 'XCoin',
XDE2: 'XDE II',
XG: 'XG Sports',
XP: 'XP',
XXX: 'XXXCoin',
XNX: 'XanaxCoin',
XAU: 'XauCoin',
XAUR: 'Xaurum',
XCASH: 'Xcash',
XNC: 'XenCoin',
XEN: 'XenixCoin',
XNN: 'Xenon',
MI: 'XiaoMiCoin',
XIOS: 'Xios',
XBY: 'XtraBYtes',
YAY: 'YAYcoin',
YAC: 'YAcCoin',
YMC: 'YamahaCoin',
YBC: 'YbCoin',
YES: 'YesCoin',
YOC: 'YoCoin',
YOVI: 'YobitVirtualCoin',
YOYOW: 'Yoyow',
Z2: 'Z2 Coin',
ZAB: 'ZABERcoin',
ZCC: 'ZCC Coin',
ZEC: 'ZCash',
ZECD: 'ZCashDarkCoin',
ZCL: 'ZClassic',
XZC: 'ZCoin',
ZLQ: 'ZLiteQubit',
ZSE: 'ZSEcoin',
ZYD: 'ZayedCoin',
ZXT: 'Zcrypt',
ZED: 'ZedCoins',
ZEIT: 'ZeitCoin',
ZEN: 'ZenCash',
ZENI: 'Zennies',
ZNA: 'Zenome',
ZER: 'Zero',
ZET2: 'Zeta2Coin',
ZET: 'ZetaCoin',
ZSC: 'Zeusshield',
ZBC: 'Zilbercoin',
ZOI: 'Zoin',
ZNE: 'ZoneCoin',
ZOOM: 'ZoomCoin',
ZRC: 'ZrCoin',
ZUR: 'Zurcoin',
BITCNY: 'bitCNY',
BITUSD: 'bitUSD',
DCS: 'deCLOUDs',
DNT: 'district0x',
ECHT: 'e-Chat',
EBTC: 'eBTC',
EBCH: 'eBitcoinCash',
EBST: 'eBoost',
ELTC2: 'eLTC',
DEM: 'eMark',
IBANK: 'iBankCoin',
ICE: 'iDice',
RLC: 'iEx.ec',
IW: 'iWallet',
IXT: 'iXledger',
UGT: 'ugChain',
VSL: 'vSlice',
WBTC: 'wBTC'
}
//https://www.coinigy.com/bitcoin-exchanges/
var coinigyexchanges = 
{
BITTREX: 'BTRX',
BLEUTRADE: 'BLEU',
'BTC MARKETS': 'BTCM',
'C-CEX': 'CCEX',
'CEX.IO': 'CXIO',
CHILEBIT: 'CHIL',
COINCHECK: 'CCJP',
COINMATE: 'MATE',
COINONE: 'CONE',
COINSBANK: 'CBNK',
CRYPTOPIA: 'CPIA',
EXMO: 'EXMO',
FOXBIT: 'FOXB',
GATECOIN: 'GATE',
GEMINI: 'GMNI',
COINBASE: 'GDAX', //assume COINBASE as GDAX
'GLOBAL DIGITAL ASSET EXCHANGE': 'GDAX',
HITBTC: 'HITB',
ITBIT: 'ITBT',
KORBIT: 'KBIT',
KRAKEN: 'KRKN',
LAKEBTC: 'LAKE',
'LIQUI.IO': 'LIQU',
LIVECOIN: 'LIVE',
MERCADOBITCOIN: 'MERC',
OKCOIN: 'OK',
'OKCOIN FUTURES': 'OKFT',
OKEX: 'OKEX',
PAYMIUM: 'PAYM',
POLONIEX: 'PLNX',
QUADRIGACX: 'QCX',
SURBITCOIN: 'SURB',
'THE ROCK': 'ROCK',
URDUBIT: 'URDU',
VAULTORO: 'GOLD',
VBTC: 'VBTC',
VIRWOX: 'VWOX',
YOBIT: 'YOBT'
}
const COINS = [
    'BITMEX:EVOL7D',
    'BITMEX:TRXXBT',
    'BITMEX:TRXXBT30M',
    'BITMEX:BADAXBT',
    'BITMEX:BADAXBT30M',
    'BITMEX:BBCHXBT',
    'BITMEX:BBCHXBT30M',
    'BITMEX:BEOSXBT',
    'BITMEX:BEOSXBT30M',
    'BITMEX:BXRPXBT',
    'BITMEX:BXRPXBT30M',
    'BITMEX:XRPM19',
    'BITMEX:BCHM19',
    'BITMEX:ADAM19',
    'BITMEX:EOSM19',
    'BITMEX:TRXM19',
    'BITMEX:XBT',
    'BITMEX:XBT30M',
    'BITMEX:XBTBON',
    'BITMEX:XBTBON8H',
    'BITMEX:XBTUSDPI',
    'BITMEX:XBTUSDPI8H',
    'BITMEX:XBTBON2H',
    'BITMEX:XBTUSDPI2H',
    'BITMEX:BXBT',
    'BITMEX:BXBT30M',
    'BITMEX:XBTJPY',
    'BITMEX:XBTJPY30M',
    'BITMEX:BXBTJPY',
    'BITMEX:BXBTJPY30M',
    'BITMEX:BVOL',
    'BITMEX:BVOL24H',
    'BITMEX:BVOL7D',
    'BITMEX:ETHBON',
    'BITMEX:ETHBON2H',
    'BITMEX:ETHBON8H',
    'BITMEX:ETHUSDPI',
    'BITMEX:ETHUSDPI2H',
    'BITMEX:ETHUSDPI8H',
    'BITMEX:BETH',
    'BITMEX:BETH30M',
    'BITMEX:BETHXBT',
    'BITMEX:BETHXBT30M',
    'BITMEX:BLTCXBT',
    'BITMEX:BLTCXBT30M',
    'BITMEX:USDBON',
    'BITMEX:USDBON8H',
    'BITMEX:USDBON2H',
    'BITMEX:BTCUSD',
    'BITMEX:XBT7D_U105',
    'BITMEX:XBT7D_D95',
    'BITMEX:XBTM19',
    'BITMEX:XBTU19',
    'BITMEX:ETH/USD',
    'BITMEX:ETHM19',
    'BITMEX:LTCM19', 
    'BITFINEX:BTCUSD',
    'BITFINEX:LTCUSD',
    'BITFINEX:LTCBTC',
    'BITFINEX:ETHUSD',
    'BITFINEX:ETHBTC',
    'BITFINEX:ETCBTC',
    'BITFINEX:ETCUSD',
    'BITFINEX:RRTUSD',
    'BITFINEX:RRTBTC',
    'BITFINEX:ZECUSD',
    'BITFINEX:ZECBTC',
    'BITFINEX:XMRUSD',
    'BITFINEX:XMRBTC',
    'BITFINEX:DASHUSD',
    'BITFINEX:DASHBTC',
    'BITFINEX:BTCEUR',
    'BITFINEX:BTCJPY',
    'BITFINEX:XRPUSD',
    'BITFINEX:XRPBTC',
    'BITFINEX:IOTAUSD',
    'BITFINEX:IOTABTC',
    'BITFINEX:IOTAETH',
    'BITFINEX:EOSUSD',
    'BITFINEX:EOSBTC',
    'BITFINEX:EOSETH',
    'BITFINEX:SANUSD',
    'BITFINEX:SANBTC',
    'BITFINEX:SANETH',
    'BITFINEX:OMGUSD',
    'BITFINEX:OMGBTC',
    'BITFINEX:OMGETH',
    'BITFINEX:NEOUSD',
    'BITFINEX:NEOBTC',
    'BITFINEX:NEOETH',
    'BITFINEX:ETPUSD',
    'BITFINEX:ETPBTC',
    'BITFINEX:ETPETH',
    'BITFINEX:QTUMUSD',
    'BITFINEX:QTUMBTC',
    'BITFINEX:QTUMETH',
    'BITFINEX:AVTUSD',
    'BITFINEX:AVTBTC',
    'BITFINEX:AVTETH',
    'BITFINEX:EDOUSD',
    'BITFINEX:EDOBTC',
    'BITFINEX:EDOETH',
    'BITFINEX:BTGUSD',
    'BITFINEX:BTGBTC',
    'BITFINEX:DATAUSD',
    'BITFINEX:DATABTC',
    'BITFINEX:DATAETH',
    'BITFINEX:QASHUSD',
    'BITFINEX:QASHBTC',
    'BITFINEX:QASHETH',
    'BITFINEX:YOYOWUSD',
    'BITFINEX:YOYOWBTC',
    'BITFINEX:YOYOWETH',
    'BITFINEX:GNTUSD',
    'BITFINEX:GNTBTC',
    'BITFINEX:GNTETH',
    'BITFINEX:SNTUSD',
    'BITFINEX:SNTBTC',
    'BITFINEX:SNTETH',
    'BITFINEX:IOTAEUR',
    'BITFINEX:BATUSD',
    'BITFINEX:BATBTC',
    'BITFINEX:BATETH',
    'BITFINEX:MANAUSD',
    'BITFINEX:MANABTC',
    'BITFINEX:MANAETH',
    'BITFINEX:FUNUSD',
    'BITFINEX:FUNBTC',
    'BITFINEX:FUNETH',
    'BITFINEX:ZRXUSD',
    'BITFINEX:ZRXBTC',
    'BITFINEX:ZRXETH',
    'BITFINEX:TNBUSD',
    'BITFINEX:TNBBTC',
    'BITFINEX:TNBETH',
    'BITFINEX:SPANKUSD',
    'BITFINEX:SPANKBTC',
    'BITFINEX:SPANKETH',
    'BITFINEX:TRXUSD',
    'BITFINEX:TRXBTC',
    'BITFINEX:TRXETH',
    'BITFINEX:RCNUSD',
    'BITFINEX:RCNBTC',
    'BITFINEX:RCNETH',
    'BITFINEX:RLCUSD',
    'BITFINEX:RLCBTC',
    'BITFINEX:RLCETH',
    'BITFINEX:AIDUSD',
    'BITFINEX:AIDBTC',
    'BITFINEX:AIDETH',
    'BITFINEX:SNGLSUSD',
    'BITFINEX:SNGLSBTC',
    'BITFINEX:SNGLSETH',
    'BITFINEX:REPUSD',
    'BITFINEX:REPBTC',
    'BITFINEX:REPETH',
    'BITFINEX:ELFUSD',
    'BITFINEX:ELFBTC',
    'BITFINEX:ELFETH',
    'BITFINEX:BTCGBP',
    'BITFINEX:ETHEUR',
    'BITFINEX:ETHJPY',
    'BITFINEX:ETHGBP',
    'BITFINEX:NEOEUR',
    'BITFINEX:NEOJPY',
    'BITFINEX:NEOGBP',
    'BITFINEX:EOSEUR',
    'BITFINEX:EOSJPY',
    'BITFINEX:EOSGBP',
    'BITFINEX:IOTAJPY',
    'BITFINEX:IOTAGBP',
    'BITFINEX:IOSTUSD',
    'BITFINEX:IOSTBTC',
    'BITFINEX:IOSTETH',
    'BITFINEX:AIONUSD',
    'BITFINEX:AIONBTC',
    'BITFINEX:AIONETH',
    'BITFINEX:REQUSD',
    'BITFINEX:REQBTC',
    'BITFINEX:REQETH',
    'BITFINEX:RDNUSD',
    'BITFINEX:RDNBTC',
    'BITFINEX:RDNETH',
    'BITFINEX:LRCUSD',
    'BITFINEX:LRCBTC',
    'BITFINEX:LRCETH',
    'BITFINEX:WAXUSD',
    'BITFINEX:WAXBTC',
    'BITFINEX:WAXETH',
    'BITFINEX:DAIUSD',
    'BITFINEX:DAIBTC',
    'BITFINEX:DAIETH',
    'BITFINEX:AGIUSD',
    'BITFINEX:AGIBTC',
    'BITFINEX:AGIETH',
    'BITFINEX:BFTUSD',
    'BITFINEX:BFTBTC',
    'BITFINEX:BFTETH',
    'BITFINEX:MTNUSD',
    'BITFINEX:MTNBTC',
    'BITFINEX:MTNETH',
    'BITFINEX:ODEUSD',
    'BITFINEX:ODEBTC',
    'BITFINEX:ODEETH',
    'BITFINEX:ANTUSD',
    'BITFINEX:ANTBTC',
    'BITFINEX:ANTETH',
    'BITFINEX:DTHUSD',
    'BITFINEX:DTHBTC',
    'BITFINEX:DTHETH',
    'BITFINEX:MITHUSD',
    'BITFINEX:MITHBTC',
    'BITFINEX:MITHETH',
    'BITFINEX:STORJUSD',
    'BITFINEX:STORJBTC',
    'BITFINEX:STORJETH',
    'BITFINEX:XLMUSD',
    'BITFINEX:XLMEUR',
    'BITFINEX:XLMJPY',
    'BITFINEX:XLMGBP',
    'BITFINEX:XLMBTC',
    'BITFINEX:XLMETH',
    'BITFINEX:XVGUSD',
    'BITFINEX:XVGEUR',
    'BITFINEX:XVGJPY',
    'BITFINEX:XVGGBP',
    'BITFINEX:XVGBTC',
    'BITFINEX:XVGETH',
    'BITFINEX:BCIUSD',
    'BITFINEX:BCIBTC',
    'BITFINEX:MKRUSD',
    'BITFINEX:MKRBTC',
    'BITFINEX:MKRETH',
    'BITFINEX:KNCUSD',
    'BITFINEX:KNCBTC',
    'BITFINEX:KNCETH',
    'BITFINEX:POAUSD',
    'BITFINEX:POABTC',
    'BITFINEX:POAETH',
    'BITFINEX:LYMUSD',
    'BITFINEX:LYMBTC',
    'BITFINEX:LYMETH',
    'BITFINEX:UTKUSD',
    'BITFINEX:UTKBTC',
    'BITFINEX:UTKETH',
    'BITFINEX:VEEUSD',
    'BITFINEX:VEEBTC',
    'BITFINEX:VEEETH',
    'BITFINEX:DADIUSD',
    'BITFINEX:DADIBTC',
    'BITFINEX:DADIETH',
    'BITFINEX:ORS GroupUSD',
    'BITFINEX:ORS GroupBTC',
    'BITFINEX:ORS GroupETH',
    'BITFINEX:AUCUSD',
    'BITFINEX:AUCBTC',
    'BITFINEX:AUCETH',
    'BITFINEX:POLYUSD',
    'BITFINEX:POLYBTC',
    'BITFINEX:POLYETH',
    'BITFINEX:FSNUSD',
    'BITFINEX:FSNBTC',
    'BITFINEX:FSNETH',
    'BITFINEX:CBTUSD',
    'BITFINEX:CBTBTC',
    'BITFINEX:CBTETH',
    'BITFINEX:ZCNUSD',
    'BITFINEX:ZCNBTC',
    'BITFINEX:ZCNETH',
    'BITFINEX:SENUSD',
    'BITFINEX:SENBTC',
    'BITFINEX:SENETH',
    'BITFINEX:NCASHUSD',
    'BITFINEX:NCASHBTC',
    'BITFINEX:NCASHETH',
    'BITFINEX:CNDUSD',
    'BITFINEX:CNDBTC',
    'BITFINEX:CNDETH',
    'BITFINEX:CTXCUSD',
    'BITFINEX:CTXCBTC',
    'BITFINEX:CTXCETH',
    'BITFINEX:PAIUSD',
    'BITFINEX:PAIBTC',
    'BITFINEX:SEERUSD',
    'BITFINEX:SEERBTC',
    'BITFINEX:SEERETH',
    'BITFINEX:ESSUSD',
    'BITFINEX:ESSBTC',
    'BITFINEX:ESSETH',
    'BITFINEX:ATMIUSD',
    'BITFINEX:ATMIBTC',
    'BITFINEX:ATMIETH',
    'BITFINEX:Hydro ProtocolUSD',
    'BITFINEX:Hydro ProtocolBTC',
    'BITFINEX:Hydro ProtocolETH',
    'BITFINEX:DTAUSD',
    'BITFINEX:DTABTC',
    'BITFINEX:DTAETH',
    'BITFINEX:IQUSD',
    'BITFINEX:IQBTC',
    'BITFINEX:IQEOS',
    'BITFINEX:WPRUSD',
    'BITFINEX:WPRBTC',
    'BITFINEX:WPRETH',
    'BITFINEX:ZILUSD',
    'BITFINEX:ZILBTC',
    'BITFINEX:ZILETH',
    'BITFINEX:BNTUSD',
    'BITFINEX:BNTBTC',
    'BITFINEX:BNTETH',
    'BITFINEX:ABYSSUSD',
    'BITFINEX:ABYSSETH',
    'BITFINEX:XRAUSD',
    'BITFINEX:XRAETH',
    'BITFINEX:MANUSD',
    'BITFINEX:MANETH',
    'BITFINEX:BBNUSD',
    'BITFINEX:BBNETH',
    'BITFINEX:NIOUSD',
    'BITFINEX:NIOETH',
    'BITFINEX:DGXUSD',
    'BITFINEX:DGXETH',
    'BITFINEX:VETUSD',
    'BITFINEX:VETBTC',
    'BITFINEX:VETETH',
    'BITFINEX:UTNPUSD',
    'BITFINEX:UTNPETH',
    'BITFINEX:TKNUSD',
    'BITFINEX:TKNETH',
    'BITFINEX:GOTUSD',
    'BITFINEX:GOTEUR',
    'BITFINEX:GOTETH',
    'BITFINEX:XTZUSD',
    'BITFINEX:XTZBTC',
    'BITFINEX:CNNUSD',
    'BITFINEX:CNNETH',
    'BITFINEX:BOXUSD',
    'BITFINEX:BOXETH',
    'BITFINEX:TRXEUR',
    'BITFINEX:TRXGBP',
    'BITFINEX:TRXJPY',
    'BITFINEX:MGOUSD',
    'BITFINEX:MGOETH',
    'BITFINEX:RTEUSD',
    'BITFINEX:RTEETH',
    'BITFINEX:YGGUSD',
    'BITFINEX:YGGETH',
    'BITFINEX:MLNUSD',
    'BITFINEX:MLNETH',
    'BITFINEX:WTCUSD',
    'BITFINEX:WTCETH',
    'BITFINEX:CSXUSD',
    'BITFINEX:CSXETH',
    'BITFINEX:OMNUSD',
    'BITFINEX:OMNBTC',
    'BITFINEX:INTUSD',
    'BITFINEX:INTETH',
    'BITFINEX:DRNUSD',
    'BITFINEX:DRNETH',
    'BITFINEX:PNKUSD',
    'BITFINEX:PNKETH',
    'BITFINEX:DGBUSD',
    'BITFINEX:DGBBTC',
    'BITFINEX:BSVUSD',
    'BITFINEX:BSVBTC',
    'BITFINEX:BCHUSD',
    'BITFINEX:BCHBTC',
    'BITFINEX:WLOUSD',
    'BITFINEX:WLOXLM',
    'BITFINEX:VLDUSD',
    'BITFINEX:VLDETH',
    'BITFINEX:ENJUSD',
    'BITFINEX:ENJETH',
    'BITFINEX:ONLUSD',
    'BITFINEX:ONLETH',
    'BITFINEX:RBTUSD',
    'BITFINEX:RBTBTC',
    'BITFINEX:USDTUSD',
    'BITFINEX:EUTEUR',
    'BITFINEX:EUTUSD',
    'BITFINEX:GUSDUSD',
    'BITFINEX:USDCUSD',
    'BITFINEX:TUSDUSD',
    'BITFINEX:PAXUSD',
    'BITFINEX:RIFUSD',
    'BITFINEX:RIFBTC',
    'BITFINEX:PASUSD',
    'BITFINEX:PASETH',
    'BITFINEX:VSYUSD',
    'BITFINEX:VSYBTC',
    'BITFINEX:ZRXDAI',
    'BITFINEX:MKRDAI',
    'BITFINEX:OMGDAI',
    'BITFINEX:BTTUSD',
    'BITFINEX:BTTBTC',
    'BITFINEX:BTCUSDT',
    'BITFINEX:ETHUSDT',
    'BITFINEX:CLOUSD',
    'BITFINEX:CLOBTC',
    'BITFINEX:IMPUSD',
    'BITFINEX:IMPETH',
    'BITFINEX:LTCUSDT',
    'BITFINEX:EOSUSDT',
    'BITFINEX:BCHUSDT',
    'BITFINEX:SCRUSD',
    'BITFINEX:SCRETH',
    'BITFINEX:GNOUSD',
    'BITFINEX:GNOETH',
    'BITFINEX:GENUSD',
    'BITFINEX:GENETH',
    'BITFINEX:ATOMUSD',
    'BITFINEX:ATOMBTC',
    'BITFINEX:ATOMETH',
    'BITFINEX:WBTUSD',
    'BITFINEX:XCHFUSD',
    'BITFINEX:EUSUSD',
    'BITFINEX:WBTETH',
    'BITFINEX:XCHFETH',
    'BITFINEX:EUSETH',
    'HITBTC:BCNBTC',
    'HITBTC:BTCUSDT',
    'HITBTC:DASHBTC',
    'HITBTC:DOGEBTC',
    'HITBTC:DOGEUSDT',
    'HITBTC:EMCBTC',
    'HITBTC:ETHBTC',
    'HITBTC:LSKBTC',
    'HITBTC:LTCBTC',
    'HITBTC:LTCUSDT',
    'HITBTC:NXTBTC',
    'HITBTC:SBDBTC',
    'HITBTC:SCBTC',
    'HITBTC:STEEMBTC',
    'HITBTC:XDNBTC',
    'HITBTC:XEMBTC',
    'HITBTC:XMRBTC',
    'HITBTC:ARDRBTC',
    'HITBTC:ZECBTC',
    'HITBTC:WAVESBTC',
    'HITBTC:MAIDBTC',
    'HITBTC:AMPBTC',
    'HITBTC:DGDBTC',
    'HITBTC:SNGLSBTC',
    'HITBTC:1STBTC',
    'HITBTC:TRSTBTC',
    'HITBTC:TIMEBTC',
    'HITBTC:GNOBTC',
    'HITBTC:REPBTC',
    'HITBTC:XMRUSDT',
    'HITBTC:DASHUSDT',
    'HITBTC:ETHUSDT',
    'HITBTC:NXTUSDT',
    'HITBTC:ZRCBTC',
    'HITBTC:BOSBTC',
    'HITBTC:DCTBTC',
    'HITBTC:ANTBTC',
    'HITBTC:AEONBTC',
    'HITBTC:GUPBTC',
    'HITBTC:PLUBTC',
    'HITBTC:LUNBTC',
    'HITBTC:TAASBTC',
    'HITBTC:NXCBTC',
    'HITBTC:EDGBTC',
    'HITBTC:RLCBTC',
    'HITBTC:SWTBTC',
    'HITBTC:TKNBTC',
    'HITBTC:WINGSBTC',
    'HITBTC:XAURBTC',
    'HITBTC:AEBTC',
    'HITBTC:PTOYBTC',
    'HITBTC:ZECUSDT',
    'HITBTC:XEMUSDT',
    'HITBTC:BCNUSDT',
    'HITBTC:XDNUSDT',
    'HITBTC:MAIDUSDT',
    'HITBTC:ETCBTC',
    'HITBTC:ETCUSDT',
    'HITBTC:PLBTBTC',
    'HITBTC:BNTBTC',
    'HITBTC:SNTETH',
    'HITBTC:CVCUSDT',
    'HITBTC:PAYETH',
    'HITBTC:OAXETH',
    'HITBTC:OMGETH',
    'HITBTC:BQXETH',
    'HITBTC:XTZBTC',
    'HITBTC:DICEBTC',
    'HITBTC:PTOYETH',
    'HITBTC:1STETH',
    'HITBTC:XAURETH',
    'HITBTC:TAASETH',
    'HITBTC:TIMEETH',
    'HITBTC:DICEETH',
    'HITBTC:SWTETH',
    'HITBTC:XMRETH',
    'HITBTC:ETCETH',
    'HITBTC:DASHETH',
    'HITBTC:ZECETH',
    'HITBTC:PLUETH',
    'HITBTC:GNOETH',
    'HITBTC:XRPBTC',
    'HITBTC:STRATUSDT',
    'HITBTC:STRATBTC',
    'HITBTC:SNCETH',
    'HITBTC:ADXETH',
    'HITBTC:DAO.CasinoETH',
    'HITBTC:EOSETH',
    'HITBTC:DENTETH',
    'HITBTC:SANETH',
    'HITBTC:EOSBTC',
    'HITBTC:EOSUSDT',
    'HITBTC:XTZETH',
    'HITBTC:XTZUSDT',
    'HITBTC:UETETH',
    'HITBTC:MYBETH',
    'HITBTC:SURETH',
    'HITBTC:IXTETH',
    'HITBTC:PLRETH',
    'HITBTC:TIXETH',
    'HITBTC:PROETH',
    'HITBTC:AVTETH',
    'HITBTC:EVXUSDT',
    'HITBTC:DLTBTC',
    'HITBTC:BNTETH',
    'HITBTC:BNTUSDT',
    'HITBTC:MANAUSDT',
    'HITBTC:DNTBTC',
    'HITBTC:FYPBTC',
    'HITBTC:OPTBTC',
    'HITBTC:TNTETH',
    'HITBTC:STXBTC',
    'HITBTC:STXETH',
    'HITBTC:STXUSDT',
    'HITBTC:TNTUSDT',
    'HITBTC:TNTBTC',
    'HITBTC:BitClaveBTC',
    'HITBTC:BitClaveETH',
    'HITBTC:BitClaveUSDT',
    'HITBTC:Bitcoin CashBTC',
    'HITBTC:Bitcoin CashETH',
    'HITBTC:Bitcoin CashUSDT',
    'HITBTC:ENGETH',
    'HITBTC:XUCUSDT',
    'HITBTC:SNCBTC',
    'HITBTC:SNCUSDT',
    'HITBTC:OAXUSDT',
    'HITBTC:OAXBTC',
    'HITBTC:ZRXBTC',
    'HITBTC:ZRXETH',
    'HITBTC:ZRXUSDT',
    'HITBTC:RVTBTC',
    'HITBTC:PPCBTC',
    'HITBTC:PPCUSDT',
    'HITBTC:QTUMETH',
    'HITBTC:IGNISETH',
    'HITBTC:BMCBTC',
    'HITBTC:BMCETH',
    'HITBTC:BMCUSDT',
    'HITBTC:CNDBTC',
    'HITBTC:CNDETH',
    'HITBTC:CNDUSDT',
    'HITBTC:CDTETH',
    'HITBTC:CDTUSDT',
    'HITBTC:FUNBTC',
    'HITBTC:FUNETH',
    'HITBTC:FUNUSDT',
    'HITBTC:HVNBTC',
    'HITBTC:HVNETH',
    'HITBTC:POEBTC',
    'HITBTC:POEETH',
    'HITBTC:AMBUSDT',
    'HITBTC:AMBETH',
    'HITBTC:AMBBTC',
    'HITBTC:HPCBTC',
    'HITBTC:PPTETH',
    'HITBTC:MTHBTC',
    'HITBTC:MTHETH',
    'HITBTC:LRCBTC',
    'HITBTC:LRCETH',
    'HITBTC:ICXBTC',
    'HITBTC:ICXETH',
    'HITBTC:NEOBTC',
    'HITBTC:NEOETH',
    'HITBTC:NEOUSDT',
    'HITBTC:CSNOBTC',
    'HITBTC:ICXUSDT',
    'HITBTC:PIXBTC',
    'HITBTC:PIXETH',
    'HITBTC:INDETH',
    'HITBTC:KICKBTC',
    'HITBTC:YOYOWBTC',
    'HITBTC:CDTBTC',
    'HITBTC:XVGBTC',
    'HITBTC:XVGETH',
    'HITBTC:XVGUSDT',
    'HITBTC:DGBBTC',
    'HITBTC:DGBETH',
    'HITBTC:DGBUSDT',
    'HITBTC:DCNBTC',
    'HITBTC:DCNETH',
    'HITBTC:DCNUSDT',
    'HITBTC:VIBEBTC',
    'HITBTC:ENJBTC',
    'HITBTC:ENJETH',
    'HITBTC:ENJUSDT',
    'HITBTC:ZSCBTC',
    'HITBTC:ZSCETH',
    'HITBTC:ZSCUSDT',
    'HITBTC:TRXBTC',
    'HITBTC:TRXETH',
    'HITBTC:TRXUSDT',
    'HITBTC:ARTBTC',
    'HITBTC:EVXBTC',
    'HITBTC:EVXETH',
    'HITBTC:SUBBTC',
    'HITBTC:SUBETH',
    'HITBTC:SUBUSDT',
    'HITBTC:WTCBTC',
    'HITBTC:ODNBTC',
    'HITBTC:BTMBTC',
    'HITBTC:BTMETH',
    'HITBTC:BTMUSDT',
    'HITBTC:LIFEBTC',
    'HITBTC:VIBBTC',
    'HITBTC:VIBETH',
    'HITBTC:VIBUSDT',
    'HITBTC:DRTETH',
    'HITBTC:STUUSDT',
    'HITBTC:OMGBTC',
    'HITBTC:PAYBTC',
    'HITBTC:PPTBTC',
    'HITBTC:SNTBTC',
    'HITBTC:BTGBTC',
    'HITBTC:BTGETH',
    'HITBTC:BTGUSDT',
    'HITBTC:SMARTBTC',
    'HITBTC:SMARTETH',
    'HITBTC:SMARTUSDT',
    'HITBTC:XUCETH',
    'HITBTC:XUCBTC',
    'HITBTC:LAETH',
    'HITBTC:EDOBTC',
    'HITBTC:EDOETH',
    'HITBTC:EDOUSDT',
    'HITBTC:HGTETH',
    'HITBTC:IXTBTC',
    'HITBTC:SCLBTC',
    'HITBTC:ATLBTC',
    'HITBTC:ETPBTC',
    'HITBTC:ETPETH',
    'HITBTC:ETPUSDT',
    'HITBTC:DRPUBTC',
    'HITBTC:NEBLBTC',
    'HITBTC:NEBLETH',
    'HITBTC:ARNBTC',
    'HITBTC:ARNETH',
    'HITBTC:STUBTC',
    'HITBTC:STUETH',
    'HITBTC:GVTETH',
    'HITBTC:BTXBTC',
    'HITBTC:LTCETH',
    'HITBTC:BCNETH',
    'HITBTC:MAIDETH',
    'HITBTC:NXTETH',
    'HITBTC:STRATETH',
    'HITBTC:XDNETH',
    'HITBTC:XEMETH',
    'HITBTC:PLRBTC',
    'HITBTC:SURBTC',
    'HITBTC:BQXBTC',
    'HITBTC:DOGEETH',
    'HITBTC:AMMBTC',
    'HITBTC:AMMETH',
    'HITBTC:AMMUSDT',
    'HITBTC:DBIXBTC',
    'HITBTC:PREBTC',
    'HITBTC:ZAPBTC',
    'HITBTC:DOVBTC',
    'HITBTC:DOVETH',
    'HITBTC:DRPUETH',
    'HITBTC:OTNBTC',
    'HITBTC:XRPETH',
    'HITBTC:XRPUSDT',
    'HITBTC:HCBTC',
    'HITBTC:LENDBTC',
    'HITBTC:LENDETH',
    'HITBTC:SPFETH',
    'HITBTC:SBTCBTC',
    'HITBTC:SBTCETH',
    'HITBTC:LOCBTC',
    'HITBTC:LOCETH',
    'HITBTC:LOCUSDT',
    'HITBTC:SWFTCBTC',
    'HITBTC:SWFTCETH',
    'HITBTC:SWFTCUSDT',
    'HITBTC:STARETH',
    'HITBTC:SBTCUSDT',
    'HITBTC:STORMBTC',
    'HITBTC:DIMETH',
    'HITBTC:DIMUSDT',
    'HITBTC:DIMBTC',
    'HITBTC:NGCBTC',
    'HITBTC:NGCETH',
    'HITBTC:NGCUSDT',
    'HITBTC:EMCETH',
    'HITBTC:EMCUSDT',
    'HITBTC:MCOBTC',
    'HITBTC:MCOETH',
    'HITBTC:MCOUSDT',
    'HITBTC:MANAETH',
    'HITBTC:MANABTC',
    'HITBTC:CPAYETH',
    'HITBTC:DATABTC',
    'HITBTC:DATAETH',
    'HITBTC:DATAUSDT',
    'HITBTC:UTTBTC',
    'HITBTC:UTTETH',
    'HITBTC:UTTUSDT',
    'HITBTC:KMDBTC',
    'HITBTC:KMDETH',
    'HITBTC:KMDUSDT',
    'HITBTC:QTUMUSDT',
    'HITBTC:QTUMBTC',
    'HITBTC:SNTUSDT',
    'HITBTC:OMGUSDT',
    'HITBTC:EKOBTC',
    'HITBTC:EKOETH',
    'HITBTC:ADXBTC',
    'HITBTC:ADXUSDT',
    'HITBTC:LSKETH',
    'HITBTC:LSKUSDT',
    'HITBTC:PLRUSDT',
    'HITBTC:SURUSDT',
    'HITBTC:BQXUSDT',
    'HITBTC:DRTUSDT',
    'HITBTC:REPETH',
    'HITBTC:REPUSDT',
    'HITBTC:WAXBTC',
    'HITBTC:WAXETH',
    'HITBTC:WAXUSDT',
    'HITBTC:C20BTC',
    'HITBTC:C20ETH',
    'HITBTC:IDHBTC',
    'HITBTC:IDHETH',
    'HITBTC:IPLBTC',
    'HITBTC:COVBTC',
    'HITBTC:COVETH',
    'HITBTC:SENTBTC',
    'HITBTC:SENTETH',
    'HITBTC:SENTUSDT',
    'HITBTC:SMTBTC',
    'HITBTC:SMTETH',
    'HITBTC:SMTUSDT',
    'HITBTC:CVHETH',
    'HITBTC:CVHUSDT',
    'HITBTC:CASBTC',
    'HITBTC:CASETH',
    'HITBTC:CASUSDT',
    'HITBTC:CHATBTC',
    'HITBTC:CHATETH',
    'HITBTC:CHATUSDT',
    'HITBTC:TRACETH',
    'HITBTC:JNTETH',
    'HITBTC:UTKBTC',
    'HITBTC:UTKETH',
    'HITBTC:UTKUSDT',
    'HITBTC:GNXETH',
    'HITBTC:CHSBBTC',
    'HITBTC:CHSBETH',
    'HITBTC:DAYBTC',
    'HITBTC:DAYETH',
    'HITBTC:DAYUSDT',
    'HITBTC:NEUBTC',
    'HITBTC:NEUETH',
    'HITBTC:NEUUSDT',
    'HITBTC:TAUBTC',
    'HITBTC:FLPBTC',
    'HITBTC:FLPETH',
    'HITBTC:FLPUSDT',
    'HITBTC:RBTC',
    'HITBTC:RETH',
    'HITBTC:EKOUSDT',
    'HITBTC:BCPTETH',
    'HITBTC:BCPTUSDT',
    'HITBTC:PKTBTC',
    'HITBTC:PKTETH',
    'HITBTC:BETRBTC',
    'HITBTC:BETRETH',
    'HITBTC:DBETBTC',
    'HITBTC:DBETETH',
    'HITBTC:DBETUSDT',
    'HITBTC:RNTBETH',
    'HITBTC:HANDETH',
    'HITBTC:HANDUSDT',
    'HITBTC:ACOETH',
    'HITBTC:CPYBTC',
    'HITBTC:CPYETH',
    'HITBTC:CHPETH',
    'HITBTC:BCPTBTC',
    'HITBTC:ACTBTC',
    'HITBTC:ACTETH',
    'HITBTC:ACTUSDT',
    'HITBTC:ADABTC',
    'HITBTC:ADAETH',
    'HITBTC:ADAUSDT',
    'HITBTC:SIGBTC',
    'HITBTC:MTXBTC',
    'HITBTC:MTXETH',
    'HITBTC:MTXUSDT',
    'HITBTC:WIZBTC',
    'HITBTC:WIZETH',
    'HITBTC:WIZUSDT',
    'HITBTC:DADIBTC',
    'HITBTC:DADIETH',
    'HITBTC:BDGETH',
    'HITBTC:DATXBTC',
    'HITBTC:DATXETH',
    'HITBTC:TRUEBTC',
    'HITBTC:DRGBTC',
    'HITBTC:DRGETH',
    'HITBTC:BANCABTC',
    'HITBTC:BANCAETH',
    'HITBTC:ZAPETH',
    'HITBTC:ZAPUSDT',
    'HITBTC:AUTOBTC',
    'HITBTC:NOAHBTC',
    'HITBTC:SOCBTC',
    'HITBTC:INSURBTC',
    'HITBTC:INSURETH',
    'HITBTC:OCNBTC',
    'HITBTC:OCNETH',
    'HITBTC:STQBTC',
    'HITBTC:STQETH',
    'HITBTC:XLMBTC',
    'HITBTC:XLMETH',
    'HITBTC:XLMUSDT',
    'HITBTC:IOTABTC',
    'HITBTC:IOTAETH',
    'HITBTC:IOTAUSDT',
    'HITBTC:DRTBTC',
    'HITBTC:BETRUSDT',
    'HITBTC:ERTBTC',
    'HITBTC:CRPTBTC',
    'HITBTC:CRPTUSDT',
    'HITBTC:MESHBTC',
    'HITBTC:MESHETH',
    'HITBTC:MESHUSDT',
    'HITBTC:IHTBTC',
    'HITBTC:IHTETH',
    'HITBTC:IHTUSDT',
    'HITBTC:SCCBTC',
    'HITBTC:YCCBTC',
    'HITBTC:DANBTC',
    'HITBTC:TELBTC',
    'HITBTC:TELETH',
    'HITBTC:BUBOBTC',
    'HITBTC:BUBOETH',
    'HITBTC:BUBOUSDT',
    'HITBTC:NCTBTC',
    'HITBTC:NCTETH',
    'HITBTC:NCTUSDT',
    'HITBTC:BMHBTC',
    'HITBTC:BANCAUSDT',
    'HITBTC:NOAHETH',
    'HITBTC:NOAHUSDT',
    'HITBTC:BERRYBTC',
    'HITBTC:BERRYETH',
    'HITBTC:BERRYUSDT',
    'HITBTC:GBXBTC',
    'HITBTC:GBXETH',
    'HITBTC:GBXUSDT',
    'HITBTC:SHIPBTC',
    'HITBTC:SHIPETH',
    'HITBTC:NANOBTC',
    'HITBTC:NANOETH',
    'HITBTC:NANOUSDT',
    'HITBTC:LinkerCoinBTC',
    'HITBTC:KINETH',
    'HITBTC:ARDRUSDT',
    'HITBTC:FOTAETH',
    'HITBTC:FOTABTC',
    'HITBTC:CVTBTC',
    'HITBTC:CVTETH',
    'HITBTC:CVTUSDT',
    'HITBTC:STQUSDT',
    'HITBTC:GNTBTC',
    'HITBTC:GNTETH',
    'HITBTC:GNTUSDT',
    'HITBTC:ADHBTC',
    'HITBTC:ADHETH',
    'HITBTC:ThemisBTC',
    'HITBTC:MITHBTC',
    'HITBTC:MITHETH',
    'HITBTC:MITHUSDT',
    'HITBTC:SUNCETH',
    'HITBTC:DADIUSDT',
    'HITBTC:TKYBTC',
    'HITBTC:ACATBTC',
    'HITBTC:ACATETH',
    'HITBTC:ACATUSDT',
    'HITBTC:BTXUSDT',
    'HITBTC:WIKIBTC',
    'HITBTC:WIKIETH',
    'HITBTC:WIKIUSDT',
    'HITBTC:ONTBTC',
    'HITBTC:ONTETH',
    'HITBTC:ONTUSDT',
    'HITBTC:FTXBTC',
    'HITBTC:FTXETH',
    'HITBTC:FRECBTC',
    'HITBTC:NAVIBTC',
    'HITBTC:FRECETH',
    'HITBTC:FRECUSDT',
    'HITBTC:VMEETH',
    'HITBTC:NAVIETH',
    'HITBTC:LNDETH',
    'HITBTC:CSMBTC',
    'HITBTC:NANJBTC',
    'HITBTC:NTKBTC',
    'HITBTC:NTKETH',
    'HITBTC:NTKUSDT',
    'HITBTC:AUCBTC',
    'HITBTC:AUCETH',
    'HITBTC:CMCTBTC',
    'HITBTC:CMCTETH',
    'HITBTC:CMCTUSDT',
    'HITBTC:MANBTC',
    'HITBTC:MANETH',
    'HITBTC:MANUSDT',
    'HITBTC:PNTBTC',
    'HITBTC:PNTETH',
    'HITBTC:FXTBTC',
    'HITBTC:NEXOBTC',
    'HITBTC:CHXBTC',
    'HITBTC:CHXETH',
    'HITBTC:CHXUSDT',
    'HITBTC:PATBTC',
    'HITBTC:PATETH',
    'HITBTC:XMCBTC',
    'HITBTC:FXTETH',
    'HITBTC:HEROBTC',
    'HITBTC:HEROETH',
    'HITBTC:XMCETH',
    'HITBTC:XMCUSDT',
    'HITBTC:FDZBTC',
    'HITBTC:FDZETH',
    'HITBTC:FDZUSDT',
    'HITBTC:SPDBTC',
    'HITBTC:SPDETH',
    'HITBTC:MITXBTC',
    'HITBTC:TIVBTC',
    'HITBTC:B2GBTC',
    'HITBTC:B2GUSDT',
    'HITBTC:ZPTBTC',
    'HITBTC:ZPTETH',
    'HITBTC:HBZBTC',
    'HITBTC:FACEBTC',
    'HITBTC:FACEETH',
    'HITBTC:HBZETH',
    'HITBTC:HBZUSDT',
    'HITBTC:ZPTUSDT',
    'HITBTC:MORPHBTC',
    'HITBTC:MORPHETH',
    'HITBTC:MORPHUSDT',
    'HITBTC:CPTBTC',
    'HITBTC:PATUSDT',
    'HITBTC:HTMLBTC',
    'HITBTC:HTMLETH',
    'HITBTC:MITXETH',
    'HITBTC:JOTBTC',
    'HITBTC:JBCBTC',
    'HITBTC:JBCETH',
    'HITBTC:BTSBTC',
    'HITBTC:BNKBTC',
    'HITBTC:KBCBTC',
    'HITBTC:KBCETH',
    'HITBTC:BNKETH',
    'HITBTC:BNKUSDT',
    'HITBTC:TIVETH',
    'HITBTC:TIVUSDT',
    'HITBTC:CSMETH',
    'HITBTC:CSMUSDT',
    'HITBTC:INKBTC',
    'HITBTC:IOSTBTC',
    'HITBTC:INKETH',
    'HITBTC:INKUSDT',
    'HITBTC:IOSTUSDT',
    'HITBTC:ZILBTC',
    'HITBTC:PMNTBTC',
    'HITBTC:ABYSSBTC',
    'HITBTC:ABYSSETH',
    'HITBTC:ZILUSDT',
    'HITBTC:BCIBTC',
    'HITBTC:PITCHBTC',
    'HITBTC:PITCHETH',
    'HITBTC:HTMLUSDT',
    'HITBTC:TDSBTC',
    'HITBTC:TDSETH',
    'HITBTC:TDSUSDT',
    'HITBTC:SBDETH',
    'HITBTC:SBDUSDT',
    'HITBTC:DPNBTC',
    'HITBTC:UUUBTC',
    'HITBTC:UUUETH',
    'HITBTC:XBPBTC',
    'HITBTC:CLNBTC',
    'HITBTC:CLNETH',
    'HITBTC:ELECBTC',
    'HITBTC:ELECETH',
    'HITBTC:ELECUSDT',
    'HITBTC:QNTUBTC',
    'HITBTC:QNTUETH',
    'HITBTC:QNTUUSDT',
    'HITBTC:IPLETH',
    'HITBTC:IPLUSDT',
    'HITBTC:CENNZBTC',
    'HITBTC:CENNZETH',
    'HITBTC:SWMBTC',
    'HITBTC:SPFUSDT',
    'HITBTC:SPFBTC',
    'HITBTC:KRMUSDT',
    'HITBTC:LCCBTC',
    'HITBTC:HGTBTC',
    'HITBTC:ETHTUSD',
    'HITBTC:BTCTUSD',
    'HITBTC:LTCTUSD',
    'HITBTC:XMRTUSD',
    'HITBTC:ZRXTUSD',
    'HITBTC:NEOTUSD',
    'HITBTC:Bitcoin CashTUSD',
    'HITBTC:USDTTUSD',
    'HITBTC:BTCDAI',
    'HITBTC:ETHDAI',
    'HITBTC:MKRDAI',
    'HITBTC:EOSDAI',
    'HITBTC:USDTDAI',
    'HITBTC:MKRBTC',
    'HITBTC:MKRETH',
    'HITBTC:MKRUSDT',
    'HITBTC:TUSDDAI',
    'HITBTC:NEODAI',
    'HITBTC:LTCDAI',
    'HITBTC:XMRDAI',
    'HITBTC:Bitcoin CashDAI',
    'HITBTC:XRPDAI',
    'HITBTC:NEXOETH',
    'HITBTC:NEXOUSDT',
    'HITBTC:DWSBTC',
    'HITBTC:DWSETH',
    'HITBTC:DWSUSDT',
    'HITBTC:APPCBTC',
    'HITBTC:APPCETH',
    'HITBTC:APPCUSDT',
    'HITBTC:BITETH',
    'HITBTC:SPCBTC',
    'HITBTC:SPCETH',
    'HITBTC:SPCUSDT',
    'HITBTC:REXBTC',
    'HITBTC:REXETH',
    'HITBTC:REXUSDT',
    'HITBTC:ELFBTC',
    'HITBTC:ELFUSDT',
    'HITBTC:BCDBTC',
    'HITBTC:BCDUSDT',
    'HITBTC:CVCOINBTC',
    'HITBTC:CVCOINETH',
    'HITBTC:CVCOINUSDT',
    'HITBTC:EDGETH',
    'HITBTC:EDGUSDT',
    'HITBTC:NLC2BTC',
    'HITBTC:COSMBTC',
    'HITBTC:COSMETH',
    'HITBTC:DASHEURS',
    'HITBTC:ZECEURS',
    'HITBTC:BTCEURS',
    'HITBTC:EOSEURS',
    'HITBTC:ETHEURS',
    'HITBTC:LTCEURS',
    'HITBTC:NEOEURS',
    'HITBTC:Bitcoin CashEURS',
    'HITBTC:XMREURS',
    'HITBTC:XRPEURS',
    'HITBTC:EURSUSDT',
    'HITBTC:EURSTUSD',
    'HITBTC:EURSDAI',
    'HITBTC:MNXUSDT',
    'HITBTC:ROXETH',
    'HITBTC:ZPRETH',
    'HITBTC:MNXBTC',
    'HITBTC:MNXETH',
    'HITBTC:KINDBTC',
    'HITBTC:KINDETH',
    'HITBTC:ENGTBTC',
    'HITBTC:ENGTETH',
    'HITBTC:PMABTC',
    'HITBTC:PMAETH',
    'HITBTC:TVBTC',
    'HITBTC:TVETH',
    'HITBTC:TVUSDT',
    'HITBTC:XCLRBTC',
    'HITBTC:BATBTC',
    'HITBTC:BATETH',
    'HITBTC:BATUSDT',
    'HITBTC:SRNBTC',
    'HITBTC:SRNETH',
    'HITBTC:SRNUSDT',
    'HITBTC:SVDBTC',
    'HITBTC:SVDETH',
    'HITBTC:SVDUSDT',
    'HITBTC:GSTBTC',
    'HITBTC:GSTETH',
    'HITBTC:GSTUSDT',
    'HITBTC:BNBBTC',
    'HITBTC:BNBETH',
    'HITBTC:BNBUSDT',
    'HITBTC:DITBTC',
    'HITBTC:DITETH',
    'HITBTC:POA20BTC',
    'HITBTC:CCLUSDT',
    'HITBTC:PROCBTC',
    'HITBTC:POA20ETH',
    'HITBTC:POA20USDT',
    'HITBTC:POA20DAI',
    'HITBTC:NIMBTC',
    'HITBTC:USEBTC',
    'HITBTC:USEETH',
    'HITBTC:DAVBTC',
    'HITBTC:DAVETH',
    'HITBTC:ABTCBTC',
    'HITBTC:NIMETH',
    'HITBTC:ABABTC',
    'HITBTC:ABAETH',
    'HITBTC:ABAUSDT',
    'HITBTC:BCNEOS',
    'HITBTC:LTCEOS',
    'HITBTC:XMREOS',
    'HITBTC:DASHEOS',
    'HITBTC:TRXEOS',
    'HITBTC:NEOEOS',
    'HITBTC:ZECEOS',
    'HITBTC:LSKEOS',
    'HITBTC:XEMEOS',
    'HITBTC:XRPEOS',
    'HITBTC:MESSEBTC',
    'HITBTC:MESSEETH',
    'HITBTC:MESSEUSDT',
    'HITBTC:CCLETH',
    'HITBTC:RCNBTC',
    'HITBTC:RCNETH',
    'HITBTC:RCNUSDT',
    'HITBTC:HMQBTC',
    'HITBTC:HMQETH',
    'HITBTC:MYSTBTC',
    'HITBTC:MYSTETH',
    'HITBTC:USDTGUSD',
    'HITBTC:BTCGUSD',
    'HITBTC:ETHGUSD',
    'HITBTC:EOSGUSD',
    'HITBTC:AXPRBTC',
    'HITBTC:AXPRETH',
    'HITBTC:TOLLBTC',
    'HITBTC:TOLLETH',
    'HITBTC:TOLLUSDT',
    'HITBTC:DAGBTC',
    'HITBTC:DAGETH',
    'HITBTC:BITSBTC',
    'HITBTC:BITSETH',
    'HITBTC:BITSUSDT',
    'HITBTC:VETBTC',
    'HITBTC:VETETH',
    'HITBTC:VETUSDT',
    'HITBTC:SILKETH',
    'HITBTC:BOXBTC',
    'HITBTC:BOXETH',
    'HITBTC:BOXEURS',
    'HITBTC:BOXEOS',
    'HITBTC:VOCOBTC',
    'HITBTC:VOCOETH',
    'HITBTC:VOCOUSDT',
    'HITBTC:PASSBTC',
    'HITBTC:PASSETH',
    'HITBTC:SLXBTC',
    'HITBTC:SLXUSDT',
    'HITBTC:PBTTBTC',
    'HITBTC:PMAUSDT',
    'HITBTC:TRADBTC',
    'HITBTC:DGTXBTC',
    'HITBTC:DGTXETH',
    'HITBTC:DGTXUSDT',
    'HITBTC:MRKBTC',
    'HITBTC:MRKETH',
    'HITBTC:DGBTUSD',
    'HITBTC:MESSEEOS',
    'HITBTC:MESSEEURS',
    'HITBTC:SNBLBTC',
    'HITBTC:OAKETH',
    'HITBTC:BCHBTC',
    'HITBTC:BCHUSDT',
    'HITBTC:BSVBTC',
    'HITBTC:BSVUSDT',
    'HITBTC:BKXBTC',
    'HITBTC:NPLCBTC',
    'HITBTC:NPLCETH',
    'HITBTC:ETNBTC',
    'HITBTC:ETNETH',
    'HITBTC:ETNUSDT',
    'HITBTC:MRSBTC',
    'HITBTC:MRSETH',
    'HITBTC:MRSUSDT',
    'HITBTC:DTRBTC',
    'HITBTC:DTRETH',
    'HITBTC:TDPBTC',
    'HITBTC:HBTETH',
    'HITBTC:PXGBTC',
    'HITBTC:PXGUSDT',
    'HITBTC:BTCPAX',
    'HITBTC:ETHPAX',
    'HITBTC:USDTPAX',
    'HITBTC:BTCUSDC',
    'HITBTC:ETHUSDC',
    'HITBTC:USDTUSDC',
    'HITBTC:TUSDUSDC',
    'HITBTC:DAIUSDC',
    'HITBTC:EOSPAX',
    'HITBTC:CLOBTC',
    'HITBTC:CLOETH',
    'HITBTC:CLOUSDT',
    'HITBTC:PETHBTC',
    'HITBTC:PETHETH',
    'HITBTC:PETHUSDT',
    'HITBTC:BRDBTC',
    'HITBTC:BRDETH',
    'HITBTC:NMRBTC',
    'HITBTC:SALTBTC',
    'HITBTC:SALTETH',
    'HITBTC:POLYBTC',
    'HITBTC:POLYETH',
    'HITBTC:POWRBTC',
    'HITBTC:POWRETH',
    'HITBTC:STORJBTC',
    'HITBTC:STORJETH',
    'HITBTC:STORJUSDT',
    'HITBTC:MLNBTC',
    'HITBTC:MLNETH',
    'HITBTC:BDGBTC',
    'HITBTC:POAETH',
    'HITBTC:POABTC',
    'HITBTC:POAUSDT',
    'HITBTC:POADAI',
    'HITBTC:KINBTC',
    'HITBTC:VEOBTC',
    'HITBTC:PLABTC',
    'HITBTC:PLAETH',
    'HITBTC:PLAUSDT',
    'HITBTC:BTTBTC',
    'HITBTC:BTTUSDT',
    'HITBTC:BTTETH',
    'HITBTC:ZENBTC',
    'HITBTC:ZENETH',
    'HITBTC:ZENUSDT',
    'HITBTC:GRINBTC',
    'HITBTC:GRINETH',
    'HITBTC:GRINUSDT',
    'HITBTC:FETBTC',
    'HITBTC:HTBTC',
    'HITBTC:HTUSDT',
    'HITBTC:XZCBTC',
    'HITBTC:XZCETH',
    'HITBTC:XZCUSDT',
    'HITBTC:VRABTC',
    'HITBTC:VRAETH',
    'HITBTC:BTCKRWB',
    'HITBTC:USDTKRWB',
    'HITBTC:WBTCETH',
    'HITBTC:CROBTC',
    'HITBTC:CROETH',
    'HITBTC:CROUSDT',
    'HITBTC:GASBTC',
    'HITBTC:GASETH',
    'HITBTC:GASUSDT',
    'HITBTC:ORMEUSBTC',
    'HITBTC:ORMEUSETH',
    'HITBTC:SWMETH',
    'HITBTC:SWMUSDT',
    'HITBTC:PREETH',
    'HITBTC:PHXBTC',
    'HITBTC:PHXETH',
    'HITBTC:PHXUSDT',
    'HITBTC:DAO.CasinoBTC',
    'HITBTC:USDTEOSDT',
    'HITBTC:BTCEOSDT',
    'HITBTC:ETHEOSDT',
    'HITBTC:EOSEOSDT',
    'HITBTC:DAIEOSDT',
    'HITBTC:NUTBTC',
    'HITBTC:NUTEOS',
    'HITBTC:NUTUSDT',
    'HITBTC:CUTEBTC',
    'HITBTC:CUTEETH',
    'HITBTC:CUTEUSDT',
    'HITBTC:CUTEEOS',
    'HITBTC:XCONBTC',
    'HITBTC:DCRBTC',
    'HITBTC:DCRETH',
    'HITBTC:DCRUSDT',
    'HITBTC:MGBTC',
    'HITBTC:MGETH',
    'HITBTC:MGEOS',
    'HITBTC:MGUSDT',
    'HITBTC:GNXBTC',
    'HITBTC:PROBTC',
    'HITBTC:EURSEOSDT',
    'HITBTC:TUSDEOSDT',
    'HITBTC:ECOINBTC',
    'HITBTC:ECOINETH',
    'HITBTC:ECOINUSDT',
    'COINBASE:BTCUSD',
    'COINBASE:LTCUSD',
    'COINBASE:ETHUSD',
    'COINBASE:BCHUSD',
    'BINANCE:ETHBTC',
    'BINANCE:LTCBTC',
    'BINANCE:BNBBTC',
    'BINANCE:NEOBTC',
    'BINANCE:QTUMETH',
    'BINANCE:EOSETH',
    'BINANCE:SNTETH',
    'BINANCE:BNTETH',
    'BINANCE:BCCBTC',
    'BINANCE:GASBTC',
    'BINANCE:BNBETH',
    'BINANCE:BTCUSDT',
    'BINANCE:ETHUSDT',
    'BINANCE:HSRBTC',
    'BINANCE:OAXETH',
    'BINANCE:DNTETH',
    'BINANCE:MCOETH',
    'BINANCE:ICNETH',
    'BINANCE:MCOBTC',
    'BINANCE:WTCBTC',
    'BINANCE:WTCETH',
    'BINANCE:LRCBTC',
    'BINANCE:LRCETH',
    'BINANCE:QTUMBTC',
    'BINANCE:YOYOWBTC',
    'BINANCE:OMGBTC',
    'BINANCE:OMGETH',
    'BINANCE:ZRXBTC',
    'BINANCE:ZRXETH',
    'BINANCE:STRATBTC',
    'BINANCE:STRATETH',
    'BINANCE:SNGLSBTC',
    'BINANCE:SNGLSETH',
    'BINANCE:BQXBTC',
    'BINANCE:BQXETH',
    'BINANCE:KNCBTC',
    'BINANCE:KNCETH',
    'BINANCE:FUNBTC',
    'BINANCE:FUNETH',
    'BINANCE:SNMBTC',
    'BINANCE:SNMETH',
    'BINANCE:NEOETH',
    'BINANCE:IOTABTC',
    'BINANCE:IOTAETH',
    'BINANCE:LINKBTC',
    'BINANCE:LINKETH',
    'BINANCE:XVGBTC',
    'BINANCE:XVGETH',
    'BINANCE:SALTBTC',
    'BINANCE:SALTETH',
    'BINANCE:MDABTC',
    'BINANCE:MDAETH',
    'BINANCE:MTLBTC',
    'BINANCE:MTLETH',
    'BINANCE:SUBBTC',
    'BINANCE:SUBETH',
    'BINANCE:EOSBTC',
    'BINANCE:SNTBTC',
    'BINANCE:ETCETH',
    'BINANCE:ETCBTC',
    'BINANCE:MTHBTC',
    'BINANCE:MTHETH',
    'BINANCE:ENGBTC',
    'BINANCE:ENGETH',
    'BINANCE:DNTBTC',
    'BINANCE:ZECBTC',
    'BINANCE:ZECETH',
    'BINANCE:BNTBTC',
    'BINANCE:ASTBTC',
    'BINANCE:ASTETH',
    'BINANCE:DASHBTC',
    'BINANCE:DASHETH',
    'BINANCE:OAXBTC',
    'BINANCE:ICNBTC',
    'BINANCE:BTGBTC',
    'BINANCE:BTGETH',
    'BINANCE:EVXBTC',
    'BINANCE:EVXETH',
    'BINANCE:REQBTC',
    'BINANCE:REQETH',
    'BINANCE:VIBBTC',
    'BINANCE:VIBETH',
    'BINANCE:HSRETH',
    'BINANCE:TRXBTC',
    'BINANCE:TRXETH',
    'BINANCE:POWRBTC',
    'BINANCE:POWRETH',
    'BINANCE:ARKBTC',
    'BINANCE:ARKETH',
    'BINANCE:YOYOWETH',
    'BINANCE:XRPBTC',
    'BINANCE:XRPETH',
    'BINANCE:MODBTC',
    'BINANCE:MODETH',
    'BINANCE:ENJBTC',
    'BINANCE:ENJETH',
    'BINANCE:STORJBTC',
    'BINANCE:STORJETH',
    'BINANCE:BNBUSDT',
    'BINANCE:VENBNB',
    'BINANCE:YOYOWBNB',
    'BINANCE:POWRBNB',
    'BINANCE:VENBTC',
    'BINANCE:VENETH',
    'BINANCE:KMDBTC',
    'BINANCE:KMDETH',
    'BINANCE:NULSBNB',
    'BINANCE:RCNBTC',
    'BINANCE:RCNETH',
    'BINANCE:RCNBNB',
    'BINANCE:NULSBTC',
    'BINANCE:NULSETH',
    'BINANCE:RDNBTC',
    'BINANCE:RDNETH',
    'BINANCE:RDNBNB',
    'BINANCE:XMRBTC',
    'BINANCE:XMRETH',
    'BINANCE:DLTBNB',
    'BINANCE:WTCBNB',
    'BINANCE:DLTBTC',
    'BINANCE:DLTETH',
    'BINANCE:AMBBTC',
    'BINANCE:AMBETH',
    'BINANCE:AMBBNB',
    'BINANCE:BCCETH',
    'BINANCE:BCCUSDT',
    'BINANCE:BCCBNB',
    'BINANCE:BATBTC',
    'BINANCE:BATETH',
    'BINANCE:BATBNB',
    'BINANCE:BCPTBTC',
    'BINANCE:BCPTETH',
    'BINANCE:BCPTBNB',
    'BINANCE:ARNBTC',
    'BINANCE:ARNETH',
    'BINANCE:GVTBTC',
    'BINANCE:GVTETH',
    'BINANCE:CDTBTC',
    'BINANCE:CDTETH',
    'BINANCE:GXSBTC',
    'BINANCE:GXSETH',
    'BINANCE:NEOUSDT',
    'BINANCE:NEOBNB',
    'BINANCE:POEBTC',
    'BINANCE:POEETH',
    'BINANCE:QSPBTC',
    'BINANCE:QSPETH',
    'BINANCE:QSPBNB',
    'BINANCE:BTSBTC',
    'BINANCE:BTSETH',
    'BINANCE:BTSBNB',
    'BINANCE:XZCBTC',
    'BINANCE:XZCETH',
    'BINANCE:XZCBNB',
    'BINANCE:LSKBTC',
    'BINANCE:LSKETH',
    'BINANCE:LSKBNB',
    'BINANCE:TNTBTC',
    'BINANCE:TNTETH',
    'BINANCE:FUELBTC',
    'BINANCE:FUELETH',
    'BINANCE:MANABTC',
    'BINANCE:MANAETH',
    'BINANCE:BCDBTC',
    'BINANCE:BCDETH',
    'BINANCE:DGDBTC',
    'BINANCE:DGDETH',
    'BINANCE:IOTABNB',
    'BINANCE:ADXBTC',
    'BINANCE:ADXETH',
    'BINANCE:ADXBNB',
    'BINANCE:ADABTC',
    'BINANCE:ADAETH',
    'BINANCE:PPTBTC',
    'BINANCE:PPTETH',
    'BINANCE:CMTBTC',
    'BINANCE:CMTETH',
    'BINANCE:CMTBNB',
    'BINANCE:XLMBTC',
    'BINANCE:XLMETH',
    'BINANCE:XLMBNB',
    'BINANCE:CNDBTC',
    'BINANCE:CNDETH',
    'BINANCE:CNDBNB',
    'BINANCE:LENDBTC',
    'BINANCE:LENDETH',
    'BINANCE:WABIBTC',
    'BINANCE:WABIETH',
    'BINANCE:WABIBNB',
    'BINANCE:LTCETH',
    'BINANCE:LTCUSDT',
    'BINANCE:LTCBNB',
    'BINANCE:TNBBTC',
    'BINANCE:TNBETH',
    'BINANCE:WAVESBTC',
    'BINANCE:WAVESETH',
    'BINANCE:WAVESBNB',
    'BINANCE:GTOBTC',
    'BINANCE:GTOETH',
    'BINANCE:GTOBNB',
    'BINANCE:ICXBTC',
    'BINANCE:ICXETH',
    'BINANCE:ICXBNB',
    'BINANCE:OSTBTC',
    'BINANCE:OSTETH',
    'BINANCE:OSTBNB',
    'BINANCE:ELFBTC',
    'BINANCE:ELFETH',
    'BINANCE:AIONBTC',
    'BINANCE:AIONETH',
    'BINANCE:AIONBNB',
    'BINANCE:NEBLBTC',
    'BINANCE:NEBLETH',
    'BINANCE:NEBLBNB',
    'BINANCE:BRDBTC',
    'BINANCE:BRDETH',
    'BINANCE:BRDBNB',
    'BINANCE:MCOBNB',
    'BINANCE:EDOBTC',
    'BINANCE:EDOETH',
    'BINANCE:WINGSBTC',
    'BINANCE:WINGSETH',
    'BINANCE:NAVBTC',
    'BINANCE:NAVETH',
    'BINANCE:NAVBNB',
    'BINANCE:LUNBTC',
    'BINANCE:LUNETH',
    'BINANCE:TRIGBTC',
    'BINANCE:TRIGETH',
    'BINANCE:TRIGBNB',
    'BINANCE:APPCBTC',
    'BINANCE:APPCETH',
    'BINANCE:APPCBNB',
    'BINANCE:VIBEBTC',
    'BINANCE:VIBEETH',
    'BINANCE:RLCBTC',
    'BINANCE:RLCETH',
    'BINANCE:RLCBNB',
    'BINANCE:INSBTC',
    'BINANCE:INSETH',
    'BINANCE:PIVXBTC',
    'BINANCE:PIVXETH',
    'BINANCE:PIVXBNB',
    'BINANCE:IOSTBTC',
    'BINANCE:IOSTETH',
    'BINANCE:CHATBTC',
    'BINANCE:CHATETH',
    'BINANCE:STEEMBTC',
    'BINANCE:STEEMETH',
    'BINANCE:STEEMBNB',
    'BINANCE:NANOBTC',
    'BINANCE:NANOETH',
    'BINANCE:NANOBNB',
    'BINANCE:VIABTC',
    'BINANCE:VIAETH',
    'BINANCE:VIABNB',
    'BINANCE:BLZBTC',
    'BINANCE:BLZETH',
    'BINANCE:BLZBNB',
    'BINANCE:AEBTC',
    'BINANCE:AEETH',
    'BINANCE:AEBNB',
    'BINANCE:RPXBTC',
    'BINANCE:RPXETH',
    'BINANCE:RPXBNB',
    'BINANCE:NCASHBTC',
    'BINANCE:NCASHETH',
    'BINANCE:NCASHBNB',
    'BINANCE:POABTC',
    'BINANCE:POAETH',
    'BINANCE:POABNB',
    'BINANCE:ZILBTC',
    'BINANCE:ZILETH',
    'BINANCE:ZILBNB',
    'BINANCE:ONTBTC',
    'BINANCE:ONTETH',
    'BINANCE:ONTBNB',
    'BINANCE:STORMBTC',
    'BINANCE:STORMETH',
    'BINANCE:STORMBNB',
    'BINANCE:QTUMBNB',
    'BINANCE:QTUMUSDT',
    'BINANCE:XEMBTC',
    'BINANCE:XEMETH',
    'BINANCE:XEMBNB',
    'BINANCE:WANBTC',
    'BINANCE:WANETH',
    'BINANCE:WANBNB',
    'BINANCE:WPRBTC',
    'BINANCE:WPRETH',
    'BINANCE:QLCBTC',
    'BINANCE:QLCETH',
    'BINANCE:SYSBTC',
    'BINANCE:SYSETH',
    'BINANCE:SYSBNB',
    'BINANCE:QLCBNB',
    'BINANCE:GRSBTC',
    'BINANCE:GRSETH',
    'BINANCE:ADAUSDT',
    'BINANCE:ADABNB',
    'BINANCE:CLOAKBTC',
    'BINANCE:CLOAKETH',
    'BINANCE:GNTBTC',
    'BINANCE:GNTETH',
    'BINANCE:GNTBNB',
    'BINANCE:LOOMBTC',
    'BINANCE:LOOMETH',
    'BINANCE:LOOMBNB',
    'BINANCE:XRPUSDT',
    'BINANCE:BCNBTC',
    'BINANCE:BCNETH',
    'BINANCE:BCNBNB',
    'BINANCE:REPBTC',
    'BINANCE:REPETH',
    'BINANCE:REPBNB',
    'BINANCE:BTCTUSD',
    'BINANCE:TUSDBTC',
    'BINANCE:ETHTUSD',
    'BINANCE:TUSDETH',
    'BINANCE:TUSDBNB',
    'BINANCE:ZENBTC',
    'BINANCE:ZENETH',
    'BINANCE:ZENBNB',
    'BINANCE:SKYBTC',
    'BINANCE:SKYETH',
    'BINANCE:SKYBNB',
    'BINANCE:EOSUSDT',
    'BINANCE:EOSBNB',
    'BINANCE:CVCBTC',
    'BINANCE:CVCETH',
    'BINANCE:CVCBNB',
    'BINANCE:THETABTC',
    'BINANCE:THETAETH',
    'BINANCE:THETABNB',
    'BINANCE:XRPBNB',
    'BINANCE:TUSDUSDT',
    'BINANCE:IOTAUSDT',
    'BINANCE:XLMUSDT',
    'BINANCE:IOTXBTC',
    'BINANCE:IOTXETH',
    'BINANCE:QKCBTC',
    'BINANCE:QKCETH',
    'BINANCE:AGIBTC',
    'BINANCE:AGIETH',
    'BINANCE:AGIBNB',
    'BINANCE:NXSBTC',
    'BINANCE:NXSETH',
    'BINANCE:NXSBNB',
    'BINANCE:ENJBNB',
    'BINANCE:DATABTC',
    'BINANCE:DATAETH',
    'BINANCE:ONTUSDT',
    'BINANCE:TRXBNB',
    'BINANCE:TRXUSDT',
    'BINANCE:ETCUSDT',
    'BINANCE:ETCBNB',
    'BINANCE:ICXUSDT',
    'BINANCE:SCBTC',
    'BINANCE:SCETH',
    'BINANCE:SCBNB',
    'BINANCE:NPXSBTC',
    'BINANCE:NPXSETH',
    'BINANCE:VENUSDT',
    'BINANCE:KEYBTC',
    'BINANCE:KEYETH',
    'BINANCE:NASBTC',
    'BINANCE:NASETH',
    'BINANCE:NASBNB',
    'BINANCE:MFTBTC',
    'BINANCE:MFTETH',
    'BINANCE:MFTBNB',
    'BINANCE:DENTBTC',
    'BINANCE:DENTETH',
    'BINANCE:ARDRBTC',
    'BINANCE:ARDRETH',
    'BINANCE:ARDRBNB',
    'BINANCE:NULSUSDT',
    'BINANCE:HOTBTC',
    'BINANCE:HOTETH',
    'BINANCE:VETBTC',
    'BINANCE:VETETH',
    'BINANCE:VETUSDT',
    'BINANCE:VETBNB',
    'BINANCE:DOCKBTC',
    'BINANCE:DOCKETH',
    'BINANCE:POLYBTC',
    'BINANCE:POLYBNB',
    'BINANCE:PHXBTC',
    'BINANCE:PHXETH',
    'BINANCE:PHXBNB',
    'BINANCE:HCBTC',
    'BINANCE:HCETH',
    'BINANCE:GOBTC',
    'BINANCE:GOBNB',
    'BINANCE:PAXBTC',
    'BINANCE:PAXBNB',
    'BINANCE:PAXUSDT',
    'BINANCE:PAXETH',
    'BINANCE:RVNBTC',
    'BINANCE:RVNBNB',
    'BINANCE:DCRBTC',
    'BINANCE:DCRBNB',
    'BINANCE:USDCBNB',
    'BINANCE:USDCBTC',
    'BINANCE:MITHBTC',
    'BINANCE:MITHBNB',
    'BINANCE:BCHBTC',
    'BINANCE:BSVBTC',
    'BINANCE:BCHUSDT',
    'BINANCE:BSVUSDT',
    'BINANCE:BNBPAX',
    'BINANCE:BTCPAX',
    'BINANCE:ETHPAX',
    'BINANCE:XRPPAX',
    'BINANCE:EOSPAX',
    'BINANCE:XLMPAX',
    'BINANCE:RENBTC',
    'BINANCE:RENBNB',
    'BINANCE:BNBTUSD',
    'BINANCE:XRPTUSD',
    'BINANCE:EOSTUSD',
    'BINANCE:XLMTUSD',
    'BINANCE:BNBUSDC',
    'BINANCE:BTCUSDC',
    'BINANCE:ETHUSDC',
    'BINANCE:XRPUSDC',
    'BINANCE:EOSUSDC',
    'BINANCE:XLMUSDC',
    'BINANCE:USDCUSDT',
    'BINANCE:ADATUSD',
    'BINANCE:TRXTUSD',
    'BINANCE:NEOTUSD',
    'BINANCE:TRXXRP',
    'BINANCE:XZCXRP',
    'BINANCE:PAXTUSD',
    'BINANCE:USDCTUSD',
    'BINANCE:USDCPAX',
    'BINANCE:LINKUSDT',
    'BINANCE:LINKTUSD',
    'BINANCE:LINKPAX',
    'BINANCE:LINKUSDC',
    'BINANCE:WAVESUSDT',
    'BINANCE:WAVESTUSD',
    'BINANCE:WAVESPAX',
    'BINANCE:WAVESUSDC',
    'BINANCE:BCHTUSD',
    'BINANCE:BCHPAX',
    'BINANCE:BCHUSDC',
    'BINANCE:BSVTUSD',
    'BINANCE:BSVPAX',
    'BINANCE:BSVUSDC',
    'BINANCE:LTCTUSD',
    'BINANCE:LTCPAX',
    'BINANCE:LTCUSDC',
    'BINANCE:TRXPAX',
    'BINANCE:TRXUSDC',
    'BINANCE:BTTBTC',
    'BINANCE:BTTBNB',
    'BINANCE:BTTUSDT',
    'BINANCE:BNBUSDS',
    'BINANCE:BTCUSDS',
    'BINANCE:USDSUSDT',
    'BINANCE:USDSPAX',
    'BINANCE:USDSTUSD',
    'BINANCE:USDSUSDC',
    'BINANCE:BTTPAX',
    'BINANCE:BTTTUSD',
    'BINANCE:BTTUSDC',
    'BINANCE:ONGBNB',
    'BINANCE:ONGBTC',
    'BINANCE:ONGUSDT',
    'BINANCE:HOTBNB',
    'BINANCE:HOTUSDT',
    'BINANCE:ZILUSDT',
    'BINANCE:ZRXBNB',
    'BINANCE:ZRXUSDT',
    'BINANCE:FETBNB',
    'BINANCE:FETBTC',
    'BINANCE:FETUSDT',
    'BINANCE:BATUSDT',
    'BINANCE:XMRBNB',
    'BINANCE:XMRUSDT',
    'BINANCE:ZECBNB',
    'BINANCE:ZECUSDT',
    'BINANCE:ZECPAX',
    'BINANCE:ZECTUSD',
    'BINANCE:ZECUSDC',
    'BINANCE:IOSTBNB',
    'BINANCE:IOSTUSDT',
    'BINANCE:CELRBNB',
    'BINANCE:CELRBTC',
    'BINANCE:CELRUSDT',
    'BINANCE:ADAPAX',
    'BINANCE:ADAUSDC',
    'BINANCE:NEOPAX',
    'BINANCE:NEOUSDC',
    'BINANCE:DASHBNB',
    'BINANCE:DASHUSDT',
    'BINANCE:NANOUSDT',
    'BINANCE:OMGBNB',
    'BINANCE:OMGUSDT',
    'BINANCE:THETAUSDT',
    'BINANCE:ENJUSDT',
    'BINANCE:MITHUSDT',
    'BINANCE:MATICBNB',
    'BINANCE:MATICBTC',
    'BINANCE:MATICUSDT',
    'BINANCE:ATOMBNB',
    'BINANCE:ATOMBTC',
    'BINANCE:ATOMUSDT',
    'BINANCE:ATOMUSDC',
    'BINANCE:ATOMPAX',
    'BINANCE:ATOMTUSD',
    'BINANCE:ETCUSDC',
    'BINANCE:ETCPAX',
    'BINANCE:ETCTUSD',
    'BINANCE:BATUSDC',
    'BINANCE:BATPAX',
    'BINANCE:BATTUSD'
];        